CREATE TABLE ENOC.ACCESO_CONFIRMAR (CODIGO_PERSONAL VARCHAR2(7) NOT NULL, MODALIDAD_ID NUMBER(2) DEFAULT 0  NOT NULL, CONSTRAINT ACCESO_CONFIRMAR_PK PRIMARY KEY (CODIGO_PERSONAL, MODALIDAD_ID));
CREATE TABLE ENOC.COMP_ASISTENCIA_ALUMNO (EVENTO_ID NUMBER(4) DEFAULT 0  NOT NULL, CODIGO_PERSONAL VARCHAR2(7) DEFAULT '0'  NOT NULL, ENTRADA VARCHAR2(1) DEFAULT 'N'  NOT NULL, SALIDA VARCHAR2(1) DEFAULT 'N'  NOT NULL, ENTRADA_HORA VARCHAR2(20) NOT NULL, SALIDA_HORA VARCHAR2(20) DEFAULT '-'  NOT NULL, PLAN_ID CHAR(8), CONSTRAINT COMP_ASISTENCIA_ALUMNO_PK PRIMARY KEY (EVENTO_ID, CODIGO_PERSONAL));
CREATE TABLE ENOC.CON_TIPO (TIPO_ID NUMBER(2) DEFAULT 0  NOT NULL, TIPO_NOMBRE VARCHAR2(100) DEFAULT '-'  NOT NULL, CONSTRAINT CON_TIPO_PK PRIMARY KEY (TIPO_ID));
CREATE TABLE ENOC.ENC_PERIODO (PERIODO_ID NUMBER(3) NOT NULL, PERIODO_NOMBRE VARCHAR2(50) NOT NULL, FECHA_INI DATE, FECHA_FIN DATE, ESTADO VARCHAR2(1), CONSTRAINT ENC_PERIODO_PK PRIMARY KEY (PERIODO_ID));
CREATE TABLE ENOC.SAUM_PRODUCTO (ID INTEGER NOT NULL, PRODUCTO VARCHAR2(45), PESO_BRUTO_G NUMBER(7,3), PESO_NETO_G NUMBER(5,2), ENERGIA_KCAL NUMBER(6,2), HC_G NUMBER(5,2), PTS_G VARCHAR2(5), LPS_G NUMBER(6,2), AGS_G NUMBER(5,2), AGM_G NUMBER(5,2), AGPG NUMBER(5,2), COL_MG NUMBER(6,2), NA_MG NUMBER(7,2), FIBRAG NUMBER(6,2), COSTO VARCHAR2(8), MARCA VARCHAR2(20), PRIMARY KEY (ID));

CREATE TABLE "ENOC"."ACCESO_OPCION"("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"OPCION_ID" VARCHAR2(4) DEFAULT '0000' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"USUARIO" VARCHAR2(7) DEFAULT '9800308' NOT NULL ENABLE,
	CONSTRAINT "ACCESO_OPCION_PK" PRIMARY KEY ("CODIGO_PERSONAL","OPCION_ID") ENABLE
);
   
CREATE TABLE "ENOC"."ACCESO_RES"("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"ADMINISTRADOR" CHAR(1) NOT NULL ENABLE,
	"COTEJADOR" CHAR(1) NOT NULL ENABLE,
	"ACCESOS" VARCHAR2(1000),
	"MODALIDAD" NUMBER(2,0),
	"USUARIO" VARCHAR2(20),
	"CLAVE" VARCHAR2(100),
	"SUPERVISOR" CHAR(1),
	"EXPIRA" DATE,
	"INGRESO" CHAR(1),
	"CONVALIDA" CHAR(1),
	"BECAS" VARCHAR2(1),
	"PORTAL_MAESTRO" VARCHAR2(1) NOT NULL ENABLE,
	"PORTAL_ALUMNO" VARCHAR2(1) NOT NULL ENABLE,
	"IDIOMA" VARCHAR2(5),
	"MENU" VARCHAR2(1) NOT NULL ENABLE,
	"ALUMNO_MOVIL" VARCHAR2(1) NOT NULL ENABLE,
	"CLAVE_INICIAL" VARCHAR2(100),
	"ESTADO" NUMBER(1,0) NOT NULL ENABLE,
	"CLAVE_HEXA" VARCHAR2(200) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."ACCESO_VALIDA" 
   ("DOCUMENTO_ID" NUMBER(7,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(8) NOT NULL ENABLE,
	"FECHA" DATE,
	"LLAVE" VARCHAR2(8) NOT NULL ENABLE,
	"CODIGO" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"TIPO" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE,
	CONSTRAINT "ACCESO_VALIDA_PK" PRIMARY KEY ("LLAVE","CODIGO_PERSONAL") ENABLE
   );
   
   CREATE TABLE "ENOC"."ACTIVOS" 
   ("EMPRESA" VARCHAR2(20),
	"FACTURA" VARCHAR2(20),
	"CODIGO" VARCHAR2(20),
	"DEPARTAMENTO" VARCHAR2(20),
	"DESCRIPCION" VARCHAR2(150),
	"POLIZA" VARCHAR2(20),
	"MARCA" VARCHAR2(100),
	"MODELO" VARCHAR2(100),
	"SERIE" VARCHAR2(100),
	"UBICACION" VARCHAR2(100),
	"RESPONSABLE" VARCHAR2(100),
	"PROVEEDOR" VARCHAR2(100),
	"TIPO" VARCHAR2(20),
	"FECHA_COMPRA" VARCHAR2(20),
	"MONTO" NUMBER(10,2),
	"ACUMULADA" NUMBER(10,2),
	"NETO" NUMBER(10,2),
	"PORCENTAJE" NUMBER(4,2)
   );
   
   CREATE TABLE "ENOC"."ACTIVOS_TMP" 
   ("EMPRESA_ID" VARCHAR2(20),
	"FACT" VARCHAR2(20),
	"CODIGO" VARCHAR2(20),
	"CENTRO_COSTO" VARCHAR2(20),
	"DESCRIPCION" VARCHAR2(1500),
	"FACTURA" VARCHAR2(20),
	"POLIZA" VARCHAR2(20),
	"MARCA" VARCHAR2(50),
	"MODELO" VARCHAR2(50),
	"SERIE" VARCHAR2(50),
	"UBICACION" VARCHAR2(1500),
	"RESPONSABLE" VARCHAR2(100),
	"PROVEEDOR" VARCHAR2(1500),
	"TIPO_ACTIVO" VARCHAR2(150),
	"PORCENTAJE" VARCHAR2(20),
	"FECHA_COMPRA" VARCHAR2(20),
	"MONTO_INVERSION" VARCHAR2(150),
	"DEPRECIACION_ACUMULADA" VARCHAR2(150),
	"VALOR_NETO" VARCHAR2(150)
   );
   
     CREATE TABLE "ENOC"."ALERTA" 
   ("COLUMN1" VARCHAR2(20)
   );
   
   CREATE TABLE "ENOC"."ALERTA_COVID" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"PAIS_UNO" NUMBER(3,0) NOT NULL ENABLE,
	"PAIS_DOS" NUMBER(3,0) NOT NULL ENABLE,
	"CIUDAD_UNO" VARCHAR2(50) NOT NULL ENABLE,
	"CIUDAD_DOS" VARCHAR2(50) NOT NULL ENABLE,
	"CONTACTO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"CONTACTO_FECHA" DATE,
	"FIEBRE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"TOS" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"CABEZA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"RESPIRAR" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"GARGANTA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"ESCURRIMIENTO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"OLFATO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"GUSTO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"CUERPO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"FECHA_DOS" DATE,
	"FECHA_UNO" DATE,
	"FOLIO" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
	CONSTRAINT "ALERTA_COVID_PK" PRIMARY KEY ("CODIGO_PERSONAL","FOLIO") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."ALERTA_DOCALUM" 
   ("PERIODO_ID" VARCHAR2(5) DEFAULT '0' NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"DOCUMENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVO" BLOB,
	"NOMBRE" VARCHAR2(200) DEFAULT '-' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6)
   );
   
     CREATE TABLE "ENOC"."ALUM_AGENDA" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"ENTREGADO" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"CARGA_ID" VARCHAR2(6) DEFAULT '0' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	CONSTRAINT "ALUM_AGENDA_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
     CREATE TABLE "ENOC"."ALUM_AGENDA_TRASPASO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"ENTREGADO" VARCHAR2(1) NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"CARGA_ID" VARCHAR2(6) NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."ALUM_ASESOR" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"ASESOR_ID" VARCHAR2(7),
	CONSTRAINT "ALUM_ASESOR_PK" PRIMARY KEY ("CODIGO_PERSONAL","PLAN_ID") ENABLE
   );
     CREATE TABLE "ENOC"."ALUM_ASESOR2" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"ASESOR_ID" VARCHAR2(7)
   );
   
     CREATE TABLE "ENOC"."ALUM_BECA" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"BECA" VARCHAR2(1) DEFAULT 'S',
	CONSTRAINT "ALUM_BECA_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
     CREATE TABLE "ENOC"."ALUM_CORREO" 
   ("NOMBRE" VARCHAR2(100),
	"APELLIDO" VARCHAR2(100),
	"CORREO" VARCHAR2(100) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(100),
	"ACTIVIDAD" VARCHAR2(100),
	"USO" VARCHAR2(100),
	"CODIGO_PERSONAL" VARCHAR2(20),
	CONSTRAINT "ALUM_CORREO_PK" PRIMARY KEY ("CORREO") ENABLE
   );
   
   CREATE TABLE "ENOC"."ALUM_COVID" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"FECHA_LLEGADA" DATE,
	"VACUNA" VARCHAR2(1) DEFAULT 'N',
	"POSITIVO_COVID" VARCHAR2(1) DEFAULT 'N',
	"SOSPECHOSO" VARCHAR2(1) DEFAULT 'N',
	"AISLAMIENTO" VARCHAR2(1),
	"FIN_AISLAMIENTO" DATE,
	"USUARIO_ALTA" VARCHAR2(7) DEFAULT '0',
	"FECHA_ALTA" DATE,
	"COMENTARIO" VARCHAR2(1500),
	"PERIODO_ID" VARCHAR2(20) NOT NULL ENABLE,
	"FECHA_POSITIVO" DATE,
	"FECHA_VACUNA" DATE,
	"TIPO" VARCHAR2(1) DEFAULT 'F' NOT NULL ENABLE,
	"FECHA_SOSPECHOSO" DATE,
	"VALIDADO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	CONSTRAINT "ALUM_COVID_PK" PRIMARY KEY ("CODIGO_PERSONAL","PERIODO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."ALUM_DIAS" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"DIAS" NUMBER,
	CONSTRAINT "ALUM_DIAS_PK" PRIMARY KEY ("CODIGO_PERSONAL","CARGA_ID","BLOQUE_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."ALUM_DOCUMENTO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"FOLIO" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) DEFAULT '0',
	"ARCHIVO" BLOB,
	"FECHA" TIMESTAMP(6),
	"ESTADO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(120),
	"TIPO" NUMBER(2,0) DEFAULT 0,
	"FECHA_CREA" TIMESTAMP(6),
	CONSTRAINT "ALUM_DOCUMENTO_PK" PRIMARY KEY ("CODIGO_PERSONAL","FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."ALUM_EGRESO2" 
   ("EVENTO_ID" NUMBER(3,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"CARRERA_ID" CHAR(5),
	"PLAN_ID" VARCHAR2(8),
	"AVANCE" CHAR(1),
	"TITULADO" CHAR(1),
	"PROMEDIO" NUMBER(5,2),
	"FECHA" DATE,
	"USUARIO" CHAR(7),
	"DIPLOMA" VARCHAR2(100) NOT NULL ENABLE
   );
     CREATE TABLE "ENOC"."ALUM_IMAGEN" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CONSENTIMIENTO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	"TIPO" VARCHAR2(1) DEFAULT 'A',
	"FECHA" TIMESTAMP(6),
	CONSTRAINT "ALUM_IMAGEN_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
   CREATE TABLE "ENOC"."ALUM_PERSONAL_BACK" 
   ("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(60) NOT NULL ENABLE,
	"APELLIDO_PATERNO" VARCHAR2(40) NOT NULL ENABLE,
	"APELLIDO_MATERNO" VARCHAR2(40) NOT NULL ENABLE,
	"NOMBRE_LEGAL" VARCHAR2(60),
	"F_NACIMIENTO" DATE NOT NULL ENABLE,
	"SEXO" CHAR(1) NOT NULL ENABLE,
	"ESTADO_CIVIL" CHAR(1),
	"RELIGION_ID" NUMBER(2,0),
	"BAUTIZADO" CHAR(1),
	"PAIS_ID" NUMBER(3,0),
	"ESTADO_ID" NUMBER(3,0),
	"CIUDAD_ID" NUMBER(3,0),
	"NACIONALIDAD" NUMBER(3,0),
	"EMAIL" VARCHAR2(50),
	"CURP" VARCHAR2(20),
	"ESTADO" CHAR(1),
	"COTEJADO" CHAR(1),
	"CODIGO_SE" VARCHAR2(30),
	"F_CREADO" DATE,
	"US_ALTA" VARCHAR2(7),
	"TELEFONO" VARCHAR2(50),
	"DIRECCION" VARCHAR2(100),
	"CLAVE_COLPORTOR" VARCHAR2(10),
	"STATUS" VARCHAR2(2),
	"VERSION" NUMBER(13,0),
	"DISCRIMINATOR_COL" VARCHAR2(5),
	"CAMPO_ID" NUMBER(13,0),
	"CREDENCIAL" VARCHAR2(10)
   );
   
     CREATE TABLE "ENOC"."ALUM_PLAN_RES" 
   ("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"PLAN_ID" CHAR(8) NOT NULL ENABLE,
	"F_INICIO" DATE NOT NULL ENABLE,
	"ESTADO" CHAR(1),
	"ESCUELA_ID" NUMBER(3,0) NOT NULL ENABLE,
	"AVANCE_ID" NUMBER(2,0),
	"PERMISO" CHAR(1),
	"EVENTO" CHAR(1),
	"F_GRADUACION" DATE,
	"F_EGRESO" DATE,
	"GRADO" NUMBER(2,0),
	"CICLO" NUMBER(2,0),
	"PRINCIPAL" CHAR(1),
	"ESCALA" NUMBER(3,0),
	"PRIMER_MATRICULA" DATE,
	"ACTUALIZADO" CHAR(1),
	"CICLO_SEP" NUMBER(2,0),
	"PROMEDIO" NUMBER(5,2) NOT NULL ENABLE,
	"CREDITOS" NUMBER(5,2) NOT NULL ENABLE
   );
     CREATE TABLE "ENOC"."ALUM_REGISTRO" 
   ("ID" NUMBER(5,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70),
	"PATERNO" VARCHAR2(70),
	"MATERNO" VARCHAR2(70),
	"CORREO" VARCHAR2(100),
	"TELEFONO" VARCHAR2(40),
	"CODIGO" VARCHAR2(20),
	"FECHA" DATE,
	"PLAN_ID" VARCHAR2(8) DEFAULT '-',
	CONSTRAINT "ALUM_REGISTRO_PK" PRIMARY KEY ("ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."ALUM_REMEDIAL" 
   ("CODIGO_PERSONAL" VARCHAR2(8) NOT NULL ENABLE,
	"CURSO_ID" VARCHAR2(15) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(20) DEFAULT 'A' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6) NOT NULL ENABLE
   );
   
    CREATE TABLE "ENOC"."ALUM_UBICACION_RES" 
   ("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"P_NOMBRE" VARCHAR2(60),
	"P_RELIGION" NUMBER(2,0),
	"P_NACIONALIDAD" NUMBER(3,0),
	"M_NOMBRE" VARCHAR2(80),
	"M_RELIGION" NUMBER(2,0),
	"M_NACIONALIDAD" NUMBER(3,0),
	"T_NOMBRE" VARCHAR2(80),
	"T_DIRECCION" VARCHAR2(100),
	"T_COLONIA" VARCHAR2(50),
	"T_CODIGO" VARCHAR2(30),
	"T_APARTADO" VARCHAR2(20),
	"T_TELEFONO" VARCHAR2(50),
	"T_EMAIL" VARCHAR2(50),
	"T_PAIS" NUMBER(3,0),
	"T_ESTADO" NUMBER(3,0),
	"T_CIUDAD" NUMBER(3,0),
	"T_CELULAR" VARCHAR2(40),
	"T_COMUNICA" CHAR(1),
	"T_EDOCD" VARCHAR2(100),
	"CODIGO_PADRE" VARCHAR2(7),
	"CODIGO_MADRE" VARCHAR2(7),
	"FECHA" DATE
   );
   
   
     CREATE TABLE "ENOC"."ARCH_DOCALUM_RES" 
   ("MATRICULA" VARCHAR2(7) NOT NULL ENABLE,
	"IDDOCUMENTO" NUMBER(3,0) NOT NULL ENABLE,
	"IDSTATUS" NUMBER(2,0) NOT NULL ENABLE,
	"FECHA" DATE,
	"CANTIDAD" NUMBER(2,0),
	"USUARIO" CHAR(7),
	"UBICACION" NUMBER(2,0)
   );
   
     CREATE TABLE "ENOC"."ARCH_GRUPO" 
   ("GRUPO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"GRUPO_NOMBRE" VARCHAR2(70) NOT NULL ENABLE,
	"COMENTARIO" VARCHAR2(700),
	CONSTRAINT "ARCH_GRUPO_PK" PRIMARY KEY ("GRUPO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."ARCH_GRUPO_DOCUMENTO" 
   ("GRUPO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"DOCUMENTO_ID" NUMBER(3,0) NOT NULL ENABLE,
	CONSTRAINT "ARCH_GRUPO_DOCUMENTO_PK" PRIMARY KEY ("GRUPO_ID","DOCUMENTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."ARCH_GRUPO_PLAN" 
   ("GRUPO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(7),
	CONSTRAINT "ARCH_GRUPO_PLAN_PK" PRIMARY KEY ("GRUPO_ID","PLAN_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."ARCH_GRUPOS_CARRERA_RES" 
   ("CARRERA" CHAR(5) NOT NULL ENABLE,
	"GRUPOS" VARCHAR2(252)
   );
     CREATE TABLE "ENOC"."ARCH_REVALIDA" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"REVALIDA" CHAR(1) DEFAULT 'N',
	"FECHA_REVALIDA" DATE,
	CONSTRAINT "ARCH_REVALIDA_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
     CREATE TABLE "ENOC"."BAJA_HLC" 
   ("EMPRESA" VARCHAR2(20),
	"CODIGO" VARCHAR2(20),
	"MOI" NUMBER(10,2),
	"ACUMULADO" NUMBER(10,2),
	"NETO" NUMBER(10,2),
	"FACTURA" VARCHAR2(30),
	"TIPO" VARCHAR2(20)
   );
   
     CREATE TABLE "ENOC"."BEC_ACUERDO_RES" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"TIPO" NUMBER(2,0) NOT NULL ENABLE,
	"FECHA" DATE,
	"MATRICULA" NUMBER(8,2),
	"ENSENANZA" NUMBER(8,2),
	"INTERNADO" NUMBER(8,2),
	"VALOR" VARCHAR2(1),
	"VIGENCIA" DATE,
	"ESTADO" VARCHAR2(1),
	"FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"ID_EJERCICIO" VARCHAR2(8) NOT NULL ENABLE,
	"PROMESA" NUMBER(8,2),
	"ID_CCOSTO" VARCHAR2(12),
	"PUESTO_ID" VARCHAR2(12),
	"HORAS" NUMBER(4,0),
	"TIPOADICIONAL" VARCHAR2(1) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(7)
   );
   
     CREATE TABLE "ENOC"."BEC_CONTRATO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"PUESTO_ID" VARCHAR2(12) NOT NULL ENABLE,
	"ARCHIVO" BLOB,
	"NOMBRE" VARCHAR2(25),
	"FECHA" DATE,
	"AUTORIZADO" TIMESTAMP(6),
	CONSTRAINT "BEC_CONTRATO_PK" PRIMARY KEY ("CODIGO_PERSONAL","PUESTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."BEC_PUESTO_ALUMNO_RES" 
   ("PUESTO_ID" VARCHAR2(12) NOT NULL ENABLE,
	"ID_EJERCICIO" VARCHAR2(8) NOT NULL ENABLE,
	"ID_CCOSTO" VARCHAR2(20) NOT NULL ENABLE,
	"CATEGORIA_ID" NUMBER(3,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7),
	"FECHA_INI" DATE,
	"FECHA_FIN" DATE,
	"TIPO" VARCHAR2(1),
	"ESTADO" VARCHAR2(1),
	"USUARIO" VARCHAR2(7),
	"NIVEL_ID" NUMBER(2,0),
	"PERIODO_ID" VARCHAR2(5) NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(100)
   );
   
     CREATE TABLE "ENOC"."BEC_PUESTO_RES" 
   ("ID_EJERCICIO" VARCHAR2(8) NOT NULL ENABLE,
	"ID_CCOSTO" VARCHAR2(20) NOT NULL ENABLE,
	"CATEGORIA_ID" NUMBER(3,0) NOT NULL ENABLE,
	"JUSTIFICACION" VARCHAR2(1000),
	"FUNCION" VARCHAR2(1000),
	"COMPETENCIAS" VARCHAR2(40),
	"CERTIFICACIONES" VARCHAR2(1000),
	"CANTIDAD" NUMBER(3,0),
	"ESTADO" VARCHAR2(1),
	"OTRAS_COMP" VARCHAR2(1500),
	"PERIODO_ID" VARCHAR2(5) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."BEC_SOLICITUD" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"POR_COORDINADOR" NUMBER(5,2),
	"COORDINADOR" VARCHAR2(7),
	"POR_COMISION" NUMBER(5,2),
	"USUARIO" VARCHAR2(7),
	"COMENTARIO" VARCHAR2(500) DEFAULT '-' NOT NULL ENABLE,
	"FECHA" DATE,
	"COM_COORDINADOR" VARCHAR2(500) DEFAULT '-' NOT NULL ENABLE,
	"PERIODO_ID" VARCHAR2(5),
	CONSTRAINT "BEC_SOLICITUD_PK" PRIMARY KEY ("CODIGO_PERSONAL","FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."BEC_SOL_PERIODO" 
   ("PERIODO_ID" VARCHAR2(5) NOT NULL ENABLE,
	"PERIODO_NOMBRE" VARCHAR2(40) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	CONSTRAINT "BEC_SOL_PERIODO_PK" PRIMARY KEY ("PERIODO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."BEC_TIPO_CARRERA" 
   (	"ID_EJERCICIO" VARCHAR2(8) DEFAULT '0' NOT NULL ENABLE,
	"TIPO" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"CARRERA_ID" VARCHAR2(5) DEFAULT '00000' NOT NULL ENABLE,
	CONSTRAINT "BEC_TIPO_CARRERA_PK" PRIMARY KEY ("ID_EJERCICIO","TIPO","CARRERA_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."BIT_REQUISITO" 
   ("REQUISITO_ID" NUMBER(4,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70),
	"TIPO" CHAR(1),
	"COMENTARIO" VARCHAR2(1500),
	CONSTRAINT "BIT_REQUISITO_PK" PRIMARY KEY ("REQUISITO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."BIT_REQUISITO_ALUMNO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"TRAMITE_ID" NUMBER(4,0) NOT NULL ENABLE,
	"REQUISITO_ID" NUMBER(4,0) NOT NULL ENABLE,
	"FECHA" DATE,
	"CODIGO_EMPLEADO" VARCHAR2(7),
	"ESTADO" VARCHAR2(1),
	"FOLIO" NUMBER(2,0) NOT NULL ENABLE,
	CONSTRAINT "BIT_REQUISITO_ALUMNO_PK" PRIMARY KEY ("CODIGO_PERSONAL","REQUISITO_ID","TRAMITE_ID","FOLIO") ENABLE
   );
     CREATE TABLE "ENOC"."BIT_SOLICITUD" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"FOLIO" NUMBER(2,0) NOT NULL ENABLE,
	"TRAMITE_ID" NUMBER(4,0),
	"STATUS" CHAR(1),
	"TEXTO_ALUMNO" VARCHAR2(1000),
	"TEXTO_ADMIN" VARCHAR2(1000),
	"FECHA" DATE,
	"FOLIO_TRAMITE" VARCHAR2(10) DEFAULT '0' NOT NULL ENABLE,
	CONSTRAINT "BIT_SOLICITUD_PK" PRIMARY KEY ("CODIGO_PERSONAL","FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."BIT_SOLICITUD2" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"FOLIO" NUMBER(2,0) NOT NULL ENABLE,
	"TRAMITE_ID" NUMBER(4,0),
	"STATUS" CHAR(1),
	"TEXTO_ALUMNO" VARCHAR2(1000),
	"TEXTO_ADMIN" VARCHAR2(1000),
	"FECHA" DATE,
	"FOLIO_TRAMITE" VARCHAR2(10) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."BIT_TRAMITE_REQUISITO" 
   ("REQUISITO_ID" NUMBER(4,0) NOT NULL ENABLE,
	"TRAMITE_ID" NUMBER(4,0) NOT NULL ENABLE,
	CONSTRAINT "BIT_REQUISITO_TRAMITE_PK" PRIMARY KEY ("REQUISITO_ID","TRAMITE_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAL_ALUMNO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) DEFAULT '0' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"NUM_PAGARE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CONFIRMAR" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"COBRO_MATRICULA" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	"SALDO" NUMBER(10,2) DEFAULT 0 NOT NULL ENABLE,
	"PORCENTAJE" NUMBER(5,2) DEFAULT 35 NOT NULL ENABLE,
	CONSTRAINT "CAL_CARGA_ALUMNO_PK" PRIMARY KEY ("CODIGO_PERSONAL","CARGA_ID","BLOQUE_ID") ENABLE
   );
     CREATE TABLE "ENOC"."CAL_CONCEPTO" 
   ("CONCEPTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"CONCEPTO_NOMBRE" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"TIPO" VARCHAR2(1) DEFAULT 'D' NOT NULL ENABLE,
	CONSTRAINT "FIN_CONCEPTO_PK" PRIMARY KEY ("CONCEPTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAL_COSTO" 
   ("COSTO_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"CONCEPTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(20) DEFAULT '0' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"TIPO" VARCHAR2(1) DEFAULT 'D' NOT NULL ENABLE,
	"IMPORTE" NUMBER(8,2) DEFAULT 0 NOT NULL ENABLE,
	"COMENTARIO" VARCHAR2(200) DEFAULT '-' NOT NULL ENABLE,
	CONSTRAINT "CAL_COSTO_PK" PRIMARY KEY ("COSTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAL_MOVIMIENTO" 
   ("MOVTO_ID" NUMBER(7,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"CONCEPTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"IMPORTE" NUMBER(8,2) DEFAULT 0 NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) DEFAULT '0' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"TIPO" VARCHAR2(1) DEFAULT 'D' NOT NULL ENABLE,
	CONSTRAINT "CAL_ALUMNO_PK" PRIMARY KEY ("MOVTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAL_PAGARE" 
   ("PAGARE_ID" NUMBER(4,0) NOT NULL ENABLE,
	"PAGARE_NOMBRE" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"FECHA" DATE,
	"CARGA_ID" VARCHAR2(6) DEFAULT '0' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	CONSTRAINT "CAL_PAGARE_PK" PRIMARY KEY ("PAGARE_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAL_PAGARE_ALUMNO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"PAGARE_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) DEFAULT '000000' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"FECHA" DATE,
	"PAGARE_NOMBRE" VARCHAR2(40) DEFAULT '-' NOT NULL ENABLE,
	"IMPORTE" NUMBER(8,2),
	CONSTRAINT "CAL_PAGARE_ALUMNO_PK" PRIMARY KEY ("CODIGO_PERSONAL","PAGARE_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAMBIO_CARRERA" 
   ("SOLICITUD_ID" NUMBER(5,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7),
	"FECHA" DATE,
	"CARRERA_BAJA" VARCHAR2(8),
	"CARRERA_ALTA" VARCHAR2(8),
	"USUARIO" VARCHAR2(7),
	CONSTRAINT "CAMBIO_CARRERA_PK" PRIMARY KEY ("SOLICITUD_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAMBIO_MATERIA" 
   ("SOLICITUD_ID" NUMBER(5,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CURSO_CARGA_ID" VARCHAR2(11) NOT NULL ENABLE,
	"CURSO_ID" VARCHAR2(15) NOT NULL ENABLE,
	"TIPO" CHAR(1) NOT NULL ENABLE,
	CONSTRAINT "CAMBIO_MATERIA_PK" PRIMARY KEY ("SOLICITUD_ID","CURSO_CARGA_ID","CURSO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAND_ALUMNO2" 
   ("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"CANDADO_ID" CHAR(4) NOT NULL ENABLE,
	"F_CREADO" DATE NOT NULL ENABLE,
	"F_BORRADO" DATE,
	"US_ALTA" CHAR(7) NOT NULL ENABLE,
	"US_BAJA" CHAR(7),
	"COMENTARIO" VARCHAR2(60),
	"ESTADO" CHAR(1),
	"PLAN_ID" VARCHAR2(8)
   );
   
     CREATE TABLE "ENOC"."CARGA_GRUPO3" 
   ("CURSO_CARGA_ID" CHAR(11) NOT NULL ENABLE,
	"CARGA_ID" CHAR(6) NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) NOT NULL ENABLE,
	"CARRERA_ID" CHAR(5) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7),
	"GRUPO" VARCHAR2(2),
	"MODALIDAD_ID" NUMBER(2,0),
	"F_INICIO" DATE,
	"F_FINAL" DATE,
	"F_ENTREGA" DATE,
	"RESTRICCION" CHAR(1) NOT NULL ENABLE,
	"ESTADO" CHAR(1),
	"HORARIO" VARCHAR2(210),
	"F_EVALUACION" DATE,
	"VALEUCAS" CHAR(1),
	"NUM_ALUM" NUMBER(3,0),
	"SEMANAS" NUMBER(3,0),
	"OPTATIVA" VARCHAR2(100),
	"COMENTARIO" VARCHAR2(40),
	"PRECIO" NUMBER(8,2),
	"CODIGO_OTRO" VARCHAR2(7),
	"MAESTRO" VARCHAR2(20)
   );
     CREATE TABLE "ENOC"."CARGA_PRACTICA" 
   ("CURSO_CARGA_ID" VARCHAR2(11) DEFAULT '000000-0000' NOT NULL ENABLE,
	"FOLIO" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"FECHA_INI" DATE,
	"FECHA_FIN" DATE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	CONSTRAINT "CARGA_PRACTICAS_PK" PRIMARY KEY ("FOLIO","CURSO_CARGA_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CARGA_PRACTICA_ALUMNO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"FOLIO" NUMBER(2,0) NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) NOT NULL ENABLE,
	"FECHA_INI" DATE,
	"FECHA_FIN" DATE,
	"COMENTARIO" VARCHAR2(500),
	"ESTADO" VARCHAR2(1) DEFAULT 'A',
	CONSTRAINT "CARGA_PRACTICA_ALUMNO_PK" PRIMARY KEY ("CODIGO_PERSONAL","FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."CAT_ESTADO2" 
   ("PAIS_ID" NUMBER(3,0) NOT NULL ENABLE,
	"ESTADO_ID" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE_ESTADO" VARCHAR2(40) NOT NULL ENABLE,
	"CORTO" VARCHAR2(20),
	"SEP_ID" VARCHAR2(2),
	"SEP_CORTO" VARCHAR2(5),
	"SEMAFORO" VARCHAR2(1) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."CAT_HORARIOFACULTAD2" 
   ("HORARIO_ID" NUMBER(7,0) NOT NULL ENABLE,
	"PERIODO" NUMBER(2,0) NOT NULL ENABLE,
	"TURNO" VARCHAR2(1),
	"HORA_INICIO" VARCHAR2(2),
	"HORA_FINAL" VARCHAR2(2),
	"MINUTO_INICIO" VARCHAR2(2),
	"MINUTO_FINAL" VARCHAR2(2),
	"NOMBRE" VARCHAR2(20),
	"TIPO" VARCHAR2(1)
   );
   
     CREATE TABLE "ENOC"."CERT_PLAN_RES" 
   ("PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"FACULTAD" VARCHAR2(100),
	"CARRERA" VARCHAR2(100),
	"NUM_CURSOS" NUMBER(3,0),
	"SEMANAS" NUMBER(2,0),
	"T_INICIAL" VARCHAR2(1000),
	"T_FINAL" VARCHAR2(1000),
	"NOTA" VARCHAR2(300),
	"PIE" VARCHAR2(200),
	"CLAVE" CHAR(1),
	"FST" CHAR(1),
	"FSP" CHAR(1),
	"COMPONENTE" NUMBER(2,0),
	"CURSO" CHAR(1),
	"RVOE" VARCHAR2(30),
	"FECHARETRO" DATE,
	"TITULO1" VARCHAR2(20),
	"TITULO2" VARCHAR2(20),
	"TITULO3" VARCHAR2(20),
	"CREDITOS" VARCHAR2(1)
   );   
   
     CREATE TABLE "ENOC"."COMP_ASISTENCIA" 
   ("EVENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	"FECHA" DATE,
	"HORA" VARCHAR2(40),
	CONSTRAINT "COMP_ASISTENCIA_PK" PRIMARY KEY ("EVENTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CON_ARCHIVO" 
   ("CONVENIO_ID" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"FOLIO" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"ARCHIVO" BLOB,
	CONSTRAINT "CON_ARCHIVO_PK" PRIMARY KEY ("CONVENIO_ID","FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."CON_CONVENIO" 
   ("ID" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(150) DEFAULT '-' NOT NULL ENABLE,
	"FECHA_FIRMA" DATE,
	"FECHA_VIGENCIA" DATE,
	"PROGRAMA" VARCHAR2(1500) DEFAULT '-' NOT NULL ENABLE,
	"OBJETIVO" VARCHAR2(1500) DEFAULT '-' NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) DEFAULT '1' NOT NULL ENABLE,
	"TIPO" VARCHAR2(1) DEFAULT '1' NOT NULL ENABLE,
	"TIPO_ID" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	CONSTRAINT "CON_CONVENIO_PK" PRIMARY KEY ("ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."CON_CONVENIO_RES" 
   ("ID" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE,
	"FECHA_FIRMA" DATE,
	"FECHA_VIGENCIA" DATE,
	"PROGRAMA" VARCHAR2(500) NOT NULL ENABLE,
	"OBJETIVO" VARCHAR2(500) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."COVID" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"PERIODO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"HIPERTENSION" VARCHAR2(1) DEFAULT 'N',
	"DIABETES" VARCHAR2(1) DEFAULT 'N',
	"CORAZON" VARCHAR2(1) DEFAULT 'N',
	"PULMON" VARCHAR2(1) DEFAULT 'N',
	"CANCER" VARCHAR2(1) DEFAULT 'N',
	"OBESIDAD" VARCHAR2(1) DEFAULT 'N',
	"ESTRES" VARCHAR2(1) DEFAULT 'N',
	"DEPRESION" VARCHAR2(1) DEFAULT 'N',
	"IMSS" VARCHAR2(1) DEFAULT 'N',
	"PASE" VARCHAR2(1) DEFAULT 'N',
	"ISSTE" VARCHAR2(1) DEFAULT 'N',
	"HLC" VARCHAR2(1) DEFAULT 'N',
	"PRIVADO" VARCHAR2(1) DEFAULT 'N',
	"NINGUNO" VARCHAR2(1) DEFAULT 'N',
	"OTRO" VARCHAR2(1) DEFAULT 'N',
	"FECHA" DATE,
	CONSTRAINT "COVID_PK" PRIMARY KEY ("CODIGO_PERSONAL","PERIODO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."COVID_PERIODO" 
   ("PERIODO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"PERIODO_NOMBRE" VARCHAR2(20) DEFAULT '-' NOT NULL ENABLE,
	"FECHA_INICIO" DATE,
	"FECHA_FINAL" DATE,
	CONSTRAINT "COVID_PERIODO_PK" PRIMARY KEY ("PERIODO_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."DIP_ALUMNO" 
   ("DIPLOMA_ID" NUMBER(4,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(20) DEFAULT '0' NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE,
	"IMAGEN_QR" BLOB,
	CONSTRAINT "DIP_ALUMNO_PK" PRIMARY KEY ("DIPLOMA_ID","CODIGO_PERSONAL") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."DIP_CURSO" 
   ("DIPLOMA_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"INSTITUCION" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"CURSO" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"TEMA" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"HORAS" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"PERIODO" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"FECHA" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"FIRMA_UNO" VARCHAR2(120) DEFAULT '-' NOT NULL ENABLE,
	"FIRMA_DOS" VARCHAR2(120) DEFAULT '-' NOT NULL ENABLE,
	"ID" VARCHAR2(20),
	CONSTRAINT "DIP_CURSO_PK" PRIMARY KEY ("DIPLOMA_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."EDIFICIO_TEMP" 
   ("EDIFICIO_ID" NUMBER(3,0) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(200),
	"FECHA" DATE,
	"MOI" NUMBER(10,2) NOT NULL ENABLE,
	"EMPRESA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"FECHA_COMPRA" VARCHAR2(10) DEFAULT '-'
   );
   
     CREATE TABLE "ENOC"."EFE_INF_EXTRA2" 
   (	"PLAN_ID" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_NOMBRE" VARCHAR2(100) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	"DIS_N_ING" NUMBER(4,0),
	"DIS_R_ING" NUMBER(4,0),
	"DIS_TOTAL" NUMBER(4,0),
	"REG_ALUM_H" NUMBER(4,0),
	"REG_ALUM_M" NUMBER(4,0),
	"REG_ALUM_T" NUMBER(4,0),
	"CUR_REM_H" NUMBER(4,0),
	"CUR_REM_M" NUMBER(4,0),
	"CUR_REM_T" NUMBER(4,0),
	"RET_SEG_H" NUMBER(4,0),
	"RET_SEG_M" NUMBER(4,0),
	"RET_SEG_T" NUMBER(4,0),
	"DESERT_H" NUMBER(4,0),
	"DESERT_M" NUMBER(4,0),
	"DESERT_T" NUMBER(4,0),
	"DESERT_19" NUMBER(4,0),
	"DESERT_20_24" NUMBER(4,0),
	"DESERT_25_29" NUMBER(4,0),
	"DESERT_30" NUMBER(4,0),
	"DESERT_DIS" NUMBER(4,0),
	"TRAB_SIM_H" NUMBER(4,0),
	"TRAB_SIM_M" NUMBER(4,0),
	"TRAB_SIM_T" NUMBER(4,0),
	"MOVIL_NAC_H" NUMBER(4,0),
	"MOVIL_NAC_M" NUMBER(4,0),
	"MOVIL_NAC_T" NUMBER(4,0),
	"MOVIL_NAC_19" NUMBER(4,0),
	"MOVIL_NAC_20_24" NUMBER(4,0),
	"MOVIL_NAC_25_29" NUMBER(4,0),
	"MOVIL_NAC_30" NUMBER(4,0),
	"MOVIL_NAC_DIS" NUMBER(4,0),
	"MOVIL_INT_H" NUMBER(4,0),
	"MOVIL_INT_M" NUMBER(4,0),
	"MOVIL_INT_T" NUMBER(4,0),
	"MOVIL_INT_19" NUMBER(4,0),
	"MOVIL_INT_20_24" NUMBER(4,0),
	"MOVIL_INT_25_29" NUMBER(4,0),
	"MOVIL_INT_30" NUMBER(4,0),
	"MOVIL_INT_DIS" NUMBER(4,0),
	"SERV_COM_H" NUMBER(4,0),
	"SERV_COM_M" NUMBER(4,0),
	"SERV_COM_T" NUMBER(4,0),
	"SERV_SOC_H" NUMBER(4,0),
	"SERV_SOC_M" NUMBER(4,0),
	"SERV_SOC_T" NUMBER(4,0),
	"EGEL" NUMBER(4,0),
	"EGEL_SOB" NUMBER(4,0),
	"TITU_PROG" NUMBER(4,0),
	"CONC" NUMBER(4,0),
	"EGRE_TRAB_H" NUMBER(4,0),
	"EGRE_TRAB_M" NUMBER(4,0),
	"EGRE_TRAB_T" NUMBER(4,0),
	"EGRE_TRAB_19" NUMBER(4,0),
	"EGRE_TRAB_20_24" NUMBER(4,0),
	"EGRE_TRAB_25_29" NUMBER(4,0),
	"EGRE_TRAB_30" NUMBER(4,0),
	"EGRE_TRAB_DIS" NUMBER(4,0),
	"DOCENTES_T" NUMBER(4,0),
	"DOCENTES_H" NUMBER(4,0),
	"DOCENTES_M" NUMBER(4,0),
	"DOCENTES_30" NUMBER(4,0),
	"DOCENTES_31_49" NUMBER(4,0),
	"DOCENTES_50" NUMBER(4,0),
	"DOCENTES_DISC" NUMBER(4,0),
	"DOCENTES_EXT" NUMBER(4,0),
	"DOCENTES_0_5" NUMBER(4,0),
	"DOCENTES_6_15" NUMBER(4,0),
	"DOCENTES_16_25" NUMBER(4,0),
	"DOCENTES_26" NUMBER(4,0),
	"DOCENTES_F_D" NUMBER(4,0),
	"DOCENTES_F_M" NUMBER(4,0),
	"DOCENTES_F_ESP" NUMBER(4,0),
	"DOCENTES_F_LIC" NUMBER(4,0),
	"DOCENTES_F_OTRO" NUMBER(4,0),
	"DOCENTES_T_COMP" NUMBER(4,0),
	"DOCENTES_COMP_H" NUMBER(4,0),
	"DOCENTES_COMP_M" NUMBER(4,0),
	"DOCENTES_MED_T" NUMBER(4,0),
	"DOCENTES_MED_H" NUMBER(4,0),
	"DOCENTES_MED_M" NUMBER(4,0),
	"DOCENTES_SNI" NUMBER(4,0),
	"DOCENTES_FPD" NUMBER(4,0),
	"DOCENTES_CGA" NUMBER(4,0),
	"DOCENTES_MOV_NAC" NUMBER(4,0),
	"DOCENTES_MOV_INT" NUMBER(4,0),
	"ASPIRANTES_ADM" NUMBER(4,0),
	"BECADOS_T" NUMBER(4,0),
	"BECADOS_H" NUMBER(4,0),
	"BECADOS_M" NUMBER(4,0),
	"ULT_GRAD_DIS" NUMBER(4,0),
	"EGRESADOS_T" NUMBER(4,0),
	"EGRESADOS_H" NUMBER(4,0),
	"EGRESADOS_M" NUMBER(4,0),
	"EGRESADOS_19" NUMBER(4,0),
	"EGRESADOS_20_24" NUMBER(4,0),
	"EGRESADOS_25_29" NUMBER(4,0),
	"EGRESADOS_30" NUMBER(4,0),
	"EGRESADOS_DIS" NUMBER(4,0),
	"TOTAL_EDAD" NUMBER(4,0),
	"TOTAL_NI_E" NUMBER(4,0),
	"NIVEL_PREV" NUMBER(4,0),
	"TOTAL_D_E" NUMBER(4,0),
	"TOTAL_D_A" NUMBER(4,0),
	"TOTAL_D_F" NUMBER(4,0),
	"QUEST_1" VARCHAR2(5),
	"TOTAL_RI_E" NUMBER(4,0),
	"TOTAL_DES_E" NUMBER(4,0),
	"TOTAL_MN_E" NUMBER(4,0),
	"TOTAL_MI_E" NUMBER(4,0),
	"QUEST_2" VARCHAR2(5),
	"TOTAL_UG_E" NUMBER(4,0),
	"TOTAL_EGRE_E" NUMBER(4,0),
	"PROM_EGRE" NUMBER(4,0),
	"QUEST_3" VARCHAR2(5),
	"QUEST_4" VARCHAR2(5),
	"TOTAL_TRAB_E" NUMBER(4,0),
	"POR_EGRE_TRAB" NUMBER(4,0)
   );
   
     CREATE TABLE "ENOC"."EMP_CONFIRMAR" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"FOLIO" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"USUARIO" VARCHAR2(7) NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	CONSTRAINT "EMP_CONFIRMAR_PK" PRIMARY KEY ("CODIGO_PERSONAL","FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."EMP_CONTACTO" 
   (	"EMPLEADO_ID" VARCHAR2(7) NOT NULL ENABLE,
	"TELEFONO" VARCHAR2(50) DEFAULT '-',
	"CORREO" VARCHAR2(100) DEFAULT '-',
	CONSTRAINT "EMP_CONTACTO_PK" PRIMARY KEY ("EMPLEADO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."EMP_CONTACTO_RES" 
   ("EMPLEADO_ID" VARCHAR2(7) NOT NULL ENABLE,
	"TELEFONO" VARCHAR2(50),
	"CORREO" VARCHAR2(100)
   );
   
     CREATE TABLE "ENOC"."EMP_CONTACTO2" 
   ("EMPLEADO_ID" VARCHAR2(7) NOT NULL ENABLE,
	"TELEFONO" VARCHAR2(50),
	"CORREO" VARCHAR2(100)
   );
   
     CREATE TABLE "ENOC"."EMP_HORAS_PRES2" 
   ("DEPARTAMENTO_ID" VARCHAR2(20) NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) NOT NULL ENABLE,
	"YEAR" VARCHAR2(20) NOT NULL ENABLE,
	"IMPORTE" NUMBER(10,2),
	"SALDO_ANT" NUMBER(10,2)
   );
   
     CREATE TABLE "ENOC"."ENC_PERIODO_RES" 
   ("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"PERIODO_ID" NUMBER(3,0) NOT NULL ENABLE,
	"FIN_ALUMNO" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"FIN_POR" VARCHAR2(4),
	"FIN_COLPOR" CHAR(1),
	"FIN_TRABAJO" CHAR(1),
	"FIN_OTRO" VARCHAR2(50),
	"REGRESAR" CHAR(1) DEFAULT 'S' NOT NULL ENABLE,
	"PRACTICAS" CHAR(1),
	"INTERNO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"EXTERNO" CHAR(1) DEFAULT 'P' NOT NULL ENABLE,
	"OBS_SALDO" CHAR(1),
	"OBS_FIN" CHAR(1),
	"OBS_MAT" CHAR(1),
	"OBS_DOC" CHAR(1),
	"OBS_SALUD" CHAR(1),
	"OBS_ADAPTACION" CHAR(1),
	"OBS_FAMILIAR" CHAR(1),
	"PLAN_ESTUDIAR" CHAR(1),
	"PLAN_OTRO_EST" VARCHAR2(100),
	"PLAN_TRABAJO" CHAR(1),
	"PLAN_COLPORTAR" CHAR(1),
	"PLAN_OTRO_TRABAJO" VARCHAR2(100),
	"PLAN_DESCANSAR" CHAR(1),
	"PLAN_NINGUNO" CHAR(1),
	"ORIENTACION" CHAR(1),
	"PLAN_ID" VARCHAR2(8) DEFAULT '0' NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."EXP_DOCUMENTO" 
   ("DOCUMENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"DOCUMENTO_NOMBRE" VARCHAR2(70) DEFAULT '-' NOT NULL ENABLE,
	"ORDEN" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"CORTO" VARCHAR2(15) DEFAULT '-' NOT NULL ENABLE,
	CONSTRAINT "EXP_DOCUMENTO_PK" PRIMARY KEY ("DOCUMENTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."EXP_EMPLEADO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT 0 NOT NULL ENABLE,
	"DOCUMENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"HOJA" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"USUARIO" VARCHAR2(7),
	"ARCHIVO" BLOB,
	"NOMBRE" VARCHAR2(200) DEFAULT '-' NOT NULL ENABLE,
	CONSTRAINT "EXP_EMPLEADO_PK" PRIMARY KEY ("CODIGO_PERSONAL","DOCUMENTO_ID","HOJA") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."EXP_TIPO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"TIPO" VARCHAR2(1) DEFAULT 'D' NOT NULL ENABLE,
	CONSTRAINT "EXP_TIPO_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."FIN_BLOQUEO" 
   ("PERIODO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	"USUARIO" VARCHAR2(7),
	CONSTRAINT "FIN_BLOQUEO_PK" PRIMARY KEY ("PERIODO_ID","CODIGO_PERSONAL") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."FIN_COSTOS" 
   ("CARGA_ID" VARCHAR2(10) NOT NULL ENABLE,
	"INTERNADO" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE,
	"COMEDOR" NUMBER(7,0),
	"MAT_MEX" NUMBER(7,0),
	"MAT_EXT" NUMBER(7,0),
	"PAGARE" NUMBER(7,0),
	"ESTADO" VARCHAR2(1),
	CONSTRAINT "FIN_COSTOS_PK" PRIMARY KEY ("CARGA_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."FIN_CREDITOS" 
   ("CARGA_ID" VARCHAR2(10) NOT NULL ENABLE,
	"DEPTO_ID" VARCHAR2(20) NOT NULL ENABLE,
	"NOR_ACFE" NUMBER(7,2) DEFAULT 0 NOT NULL ENABLE,
	"NOR_NOACFE" NUMBER(7,2),
	"DIA_ACFE" NUMBER(7,2),
	"DIA_NOACFE" NUMBER(7,2),
	CONSTRAINT "FIN_CALCULADORA_PK" PRIMARY KEY ("CARGA_ID","DEPTO_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."FIN_MARATUM" 
   ("ID" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"ARCHIVO" BLOB,
	"USUARIO" VARCHAR2(7),
	"ESTADO" VARCHAR2(1) DEFAULT 'S',
	"NOMBRE" VARCHAR2(100) DEFAULT '-',
	"PLAN_ID" VARCHAR2(8) DEFAULT '00000000' NOT NULL ENABLE,
	CONSTRAINT "FIN_MARATUM_PK" PRIMARY KEY ("ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."INS_ALUMNO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) DEFAULT '000000' NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) DEFAULT '00000000' NOT NULL ENABLE,
	"CICLO" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"MATERIAS" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	CONSTRAINT "INS_ALUMNO_PK" PRIMARY KEY ("CODIGO_PERSONAL","CARGA_ID","CICLO","PLAN_ID") ENABLE
   );
     
     
       CREATE TABLE "ENOC"."KRDX_MAXIMO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CURSO_CARGA_ID" VARCHAR2(11) NOT NULL ENABLE,
	"EVALUADAS" NUMBER(5,2),
	"PUNTOS" NUMBER(5,2),
	"MAXIMO" NUMBER(5,2),
	"CARRERA_ID" VARCHAR2(5) DEFAULT '00000' NOT NULL ENABLE,
	CONSTRAINT "KRDX_MAXIMO_PK" PRIMARY KEY ("CODIGO_PERSONAL","CURSO_CARGA_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."MAESTRO_RANGO" 
   (	"CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"YEAR" NUMBER(4,0) DEFAULT 2000 NOT NULL ENABLE,
	"RANGO_ANTERIOR" VARCHAR2(50) DEFAULT '-',
	"RESPUESTA" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"RANGO_RECOMENDADO" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"AREA" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100),
	CONSTRAINT "MAESTRO_RANGO_PK" PRIMARY KEY ("CODIGO_PERSONAL","YEAR") ENABLE
   );
   
     CREATE TABLE "ENOC"."MAT_ALUMNO" 
   ("EVENTO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"FECHA" DATE,
	"USUARIO" VARCHAR2(7),
	"MODO" VARCHAR2(1) DEFAULT 'V' NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) DEFAULT 'P' NOT NULL ENABLE,
	CONSTRAINT "ALTA_EVENTO_PK" PRIMARY KEY ("EVENTO_ID","CODIGO_PERSONAL","PLAN_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."MAT_ALUMNO2" 
   ("EVENTO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"FECHA" DATE,
	"USUARIO" VARCHAR2(7)
   );
   
   
     CREATE TABLE "ENOC"."MAT_COSTOS" 
   ("EVENTO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"MATRICULA" VARCHAR2(7) NOT NULL ENABLE,
	"CREDITOS" NUMBER(2,0),
	"CARGA_ID" VARCHAR2(6) DEFAULT '0' NOT NULL ENABLE,
	CONSTRAINT "MAT_COSTOS_PK" PRIMARY KEY ("EVENTO_ID","MATRICULA") ENABLE
   );
   
     CREATE TABLE "ENOC"."MAT_EVENTO" 
   (	"EVENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"EVENTO_NOMBRE" VARCHAR2(50) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	CONSTRAINT "MAT_EVENTO_PK" PRIMARY KEY ("EVENTO_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."MAT_INGRESO" 
   ("EVENTO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"MATRICULA" VARCHAR2(7) NOT NULL ENABLE,
	"PROPIOS" NUMBER(8,2),
	"BECARIO" NUMBER(8,2),
	"COLPORTAJE" NUMBER(8,2),
	"OTRO" NUMBER(8,2),
	CONSTRAINT "MAT_INGRESO_PK" PRIMARY KEY ("EVENTO_ID","MATRICULA") ENABLE
   );
   
     CREATE TABLE "ENOC"."MENT_ALUMNO_RES" 
   ("PERIODO_ID" CHAR(4) NOT NULL ENABLE,
	"MENTOR_ID" CHAR(7) NOT NULL ENABLE,
	"CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"FECHA" DATE,
	"STATUS" CHAR(1),
	"CARRERA_ID" CHAR(5),
	"FECHA_INICIO" DATE,
	"FECHA_FINAL" DATE,
	"FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."MENT_ENCUESTA" 
   ("ENCUESTA_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100) DEFAULT '-' NOT NULL ENABLE,
	"FECHA_INI" DATE,
	"FECHA_FIN" DATE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A',
	CONSTRAINT "MENT_ENCUESTA_PK" PRIMARY KEY ("ENCUESTA_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."MENT_PREGUNTA" 
   ("PREGUNTA_ID" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(200) DEFAULT '-' NOT NULL ENABLE,
	"ENCUESTA_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	CONSTRAINT "MENT_PREGUNTA_PK" PRIMARY KEY ("PREGUNTA_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."MENT_RESPUESTA" 
   ("CODIGO_PERSONAL" VARCHAR2(8) DEFAULT '0' NOT NULL ENABLE,
	"PREGUNTA_ID" NUMBER(7,0) NOT NULL ENABLE,
	"IMPORTANCIA" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"SATISFACCION" NUMBER(2,0) NOT NULL ENABLE,
	"ENCUESTA_ID" NUMBER(4,0) NOT NULL ENABLE,
	CONSTRAINT "MENT_RESPUESTA_PK" PRIMARY KEY ("CODIGO_PERSONAL","PREGUNTA_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."MOD_CICLO" 
   (	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CARGA_ID" VARCHAR2(6) DEFAULT '0' NOT NULL ENABLE,
	"BLOQUE_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) DEFAULT 'X' NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	CONSTRAINT "MOD_CICLO_PK" PRIMARY KEY ("CODIGO_PERSONAL","CARGA_ID","BLOQUE_ID","PLAN_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."MOD_NOTA" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CURSO_CARGA_ID" VARCHAR2(11) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	CONSTRAINT "MOD_NOTA_PK" PRIMARY KEY ("CODIGO_PERSONAL","CURSO_CARGA_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."MOD_PROMEDIO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) DEFAULT 'X' NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6),
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	CONSTRAINT "ALUM_PROMEDIO_PK" PRIMARY KEY ("CODIGO_PERSONAL","PLAN_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."MODULO_JSP_RES" 
   ("ID" NUMBER(7,0),
	"RUTA" VARCHAR2(200) NOT NULL ENABLE,
	"ENOC" VARCHAR2(1) NOT NULL ENABLE,
	"ATLAS" VARCHAR2(1) NOT NULL ENABLE,
	"RUTA_CORTA" VARCHAR2(100) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."MODULO_OPCION_RES" 
   ("MODULO_ID" CHAR(3) NOT NULL ENABLE,
	"OPCION_ID" VARCHAR2(4) NOT NULL ENABLE,
	"NOMBRE_OPCION" VARCHAR2(40) NOT NULL ENABLE,
	"URL" VARCHAR2(100),
	"ICONO" VARCHAR2(100),
	"ORDEN" NUMBER(2,0),
	"MAPA" CHAR(3),
	"CARPETA" VARCHAR2(100),
	"USUARIOS" CLOB
    );
   
     CREATE TABLE "ENOC"."NOTI_MENSAJES" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"ID" NUMBER(8,0) NOT NULL ENABLE,
	"TIPO" NUMBER(2,0),
	"MENSAJE" VARCHAR2(500),
	"URL" VARCHAR2(300),
	"SILENCIADO" VARCHAR2(1) DEFAULT 'N',
	"VISTO" VARCHAR2(1) DEFAULT 'N',
	"FECHA" TIMESTAMP(6),
	"SMS" VARCHAR2(1) DEFAULT 'N',
	CONSTRAINT "NOTI_MENSAJES_PK" PRIMARY KEY ("ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."NOTI_PROCESO_PENDIENTE" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"ID" NUMBER(8,0) NOT NULL ENABLE,
	"TIPO" NUMBER(2,0),
	"FECHA_INICIO" TIMESTAMP(6),
	"DATOS" VARCHAR2(100) DEFAULT '-',
	CONSTRAINT "NOTI_PROCESO_PENDIENTE_PK" PRIMARY KEY ("ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."NSE_ENCUESTA" 
   ("ENCUESTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"ENCUESTA_NOMBRE" VARCHAR2(50) DEFAULT '-',
	"FECHA_INI" DATE,
	"FECHA_FIN" DATE,
	CONSTRAINT "NSE_ENCUESTA_PK" PRIMARY KEY ("ENCUESTA_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."NSE_PREGUNTA" 
   (	"PREGUNTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"ENCUESTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"PREGUNTA" VARCHAR2(300),
	CONSTRAINT "NSE_PREGUNTA_PK" PRIMARY KEY ("PREGUNTA_ID","ENCUESTA_ID") ENABLE
   );
     CREATE TABLE "ENOC"."NSE_RESPUESTA" 
   ("PREGUNTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"RESPUESTA" VARCHAR2(30),
	"PUNTOS" VARCHAR2(3),
	"ENCUESTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	CONSTRAINT "NSE_RESPUESTA_PK" PRIMARY KEY ("PREGUNTA_ID","CODIGO_PERSONAL","ENCUESTA_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."NSE_RESPUESTAOLD" 
   ("PREGUNTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"RESPUESTA" VARCHAR2(30),
	"PUNTOS" VARCHAR2(3),
	"ENCUESTA_ID" NUMBER(2,0) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."NSE_RESPUESTA_PREGUNTA" 
   ("RESPUESTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"ENCUESTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"PREGUNTA_ID" NUMBER(2,0) NOT NULL ENABLE,
	"RESPUESTA" VARCHAR2(30),
	"PUNTOS" NUMBER(3,0) NOT NULL ENABLE,
	CONSTRAINT "NSE_RESPUESTA_PREGUNTA_PK" PRIMARY KEY ("RESPUESTA_ID","ENCUESTA_ID","PREGUNTA_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."RES_ALUMNO" 
   ("MATRICULA" VARCHAR2(7) NOT NULL ENABLE,
	"CALLE" VARCHAR2(70),
	"COLONIA" VARCHAR2(20),
	"MUNICIPIO" VARCHAR2(20),
	"TEL_AREA" VARCHAR2(7),
	"TEL_NUMERO" VARCHAR2(12),
	"TUT_NOMBRE" VARCHAR2(20),
	"TUT_APELLIDOS" VARCHAR2(20),
	"RAZON" NUMBER(2,0),
	"USUARIO" VARCHAR2(10),
	"FECHA" DATE,
	"NUMERO" VARCHAR2(15),
	"PERIODO_ID" NUMBER(5,0) NOT NULL ENABLE,
	"RESIDENCIA_ID" VARCHAR2(1),
	"DORMITORIO" NUMBER(1,0),
	"FECHA_INICIO" DATE,
	"FECHA_FINAL" DATE,
	"FOLIO" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
	"ESPERMANENTE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	CONSTRAINT "RES_ALUMNO_PK" PRIMARY KEY ("MATRICULA","FOLIO") ENABLE
   );
     CREATE TABLE "ENOC"."RES_ALUMNO2" 
   ("MATRICULA" VARCHAR2(7) NOT NULL ENABLE,
	"CALLE" VARCHAR2(70),
	"COLONIA" VARCHAR2(20),
	"MUNICIPIO" VARCHAR2(20),
	"TEL_AREA" VARCHAR2(7),
	"TEL_NUMERO" VARCHAR2(12),
	"TUT_NOMBRE" VARCHAR2(20),
	"TUT_APELLIDOS" VARCHAR2(20),
	"RAZON" NUMBER(2,0),
	"USUARIO" VARCHAR2(10),
	"FECHA" DATE,
	"NUMERO" VARCHAR2(15),
	"PERIODO_ID" NUMBER(5,0) NOT NULL ENABLE,
	"RESIDENCIA_ID" VARCHAR2(1),
	"DORMITORIO" NUMBER(1,0),
	"FECHA_INICIO" DATE,
	"FECHA_FINAL" DATE,
	"FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"ESPERMANENTE" VARCHAR2(1) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."RES_DOCUMENTO" 
   ("FOLIO" NUMBER(6,0) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(200) DEFAULT '-' NOT NULL ENABLE,
	"DOCUMENTO" BLOB,
	"FOLIO_EXPEDIENTE" NUMBER(6,0),
	"NOMBRE" VARCHAR2(100),
	"FECHA" TIMESTAMP(6),
	CONSTRAINT "RES_DOCUMENTO_PK" PRIMARY KEY ("FOLIO") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."RES_EXPEDIENTE" 
   ("FOLIO" NUMBER(6,0) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(200),
	"ESTADO" CHAR(1) DEFAULT 'E' NOT NULL ENABLE,
	"FECHA" DATE,
	"PLAN_ID" VARCHAR2(8) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"COMENTARIO" VARCHAR2(1500) DEFAULT '-' NOT NULL ENABLE,
	CONSTRAINT "RES_EXPEDIENTE_PK" PRIMARY KEY ("FOLIO") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."RES_HOSPEDAJE" 
   ("ID" NUMBER(5,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) DEFAULT '-',
	"APELLIDOS" VARCHAR2(70) DEFAULT '-',
	"NOMINA" VARCHAR2(7) DEFAULT '0',
	"DIRECCION" VARCHAR2(100) DEFAULT '-',
	"TELEFONO" VARCHAR2(20) DEFAULT '-',
	"CUPO_HOMBRES" NUMBER(2,0),
	"CUPO_MUJERES" NUMBER(2,0),
	"CUARTOS" NUMBER DEFAULT 0,
	"ESTADO" VARCHAR2(1) DEFAULT 'A'
   );
   
   
     CREATE TABLE "ENOC"."RES_PERIODO" 
   ("PERIODO_ID" NUMBER(5,0) NOT NULL ENABLE,
	"PERIODO_NOMBRE" VARCHAR2(70) DEFAULT '-' NOT NULL ENABLE,
	"FECHA_INI" DATE NOT NULL ENABLE,
	"FECHA_FIN" DATE,
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	CONSTRAINT "RES_PERIODO_PK" PRIMARY KEY ("PERIODO_ID") ENABLE
   );
   
   
   
     CREATE TABLE "ENOC"."SAII_ALUMNO" 
   ("PLANTEL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_SEP" VARCHAR2(20),
	"CICLO" NUMBER(2,0),
	"CURP" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"PATERNO" VARCHAR2(70),
	"MATERNO" VARCHAR2(70),
	"FECHA" DATE NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_UM" VARCHAR2(40),
	"GENERO" VARCHAR2(1),
	"EDAD" NUMBER(4,0),
	"GRADO" NUMBER(2,0),
	"PAIS_ID" NUMBER(3,0),
	"ESTADO_ID" NUMBER(3,0),
	"PREPA_LUGAR" NUMBER(2,0),
	"USADO" VARCHAR2(1),
	"FOLIO" NUMBER(7,0) NOT NULL ENABLE,
	CONSTRAINT "SAII_ALUMNO_PK" PRIMARY KEY ("FOLIO") ENABLE
   );
   
     CREATE TABLE "ENOC"."SAII_GRUPO" 
   ("GRUPO_ID" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE,
	"PERIODO_ID" VARCHAR2(5) DEFAULT '-' NOT NULL ENABLE,
	"PLAN_ID" VARCHAR2(8) DEFAULT 'X' NOT NULL ENABLE,
	CONSTRAINT "SAII_GRUPO_PK" PRIMARY KEY ("PERIODO_ID","PLAN_ID") ENABLE
   );
    
    
      CREATE TABLE "ENOC"."SAL_CLUB_RES" 
   ("GRUPO_ID" NUMBER(4,0) NOT NULL ENABLE,
	"GRUPO_NOMBRE" VARCHAR2(100) NOT NULL ENABLE,
	"RESPONSABLE" VARCHAR2(100),
	"ALUMNOS" VARCHAR2(2500)
   );
   
   
     CREATE TABLE "ENOC"."SAL_PROPOSITO" 
   ("PROPOSITO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"PROPOSITO_NOMBRE" VARCHAR2(50) DEFAULT '-' NOT NULL ENABLE,
	"LETRA" VARCHAR2(20) DEFAULT 'X',
	CONSTRAINT "SAL_PROPOSITO_PK" PRIMARY KEY ("PROPOSITO_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_ALUMNO_OLD" 
   ("PLANTEL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_SEP" VARCHAR2(20),
	"CICLO" NUMBER(2,0),
	"CURP" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"PATERNO" VARCHAR2(70),
	"MATERNO" VARCHAR2(70),
	"FECHA" DATE NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_UM" VARCHAR2(40),
	"GENERO" VARCHAR2(1),
	"EDAD" NUMBER(4,0),
	"GRADO" NUMBER(2,0),
	"PAIS_ID" NUMBER(3,0),
	"ESTADO_ID" NUMBER(3,0),
	"PREPA_LUGAR" NUMBER(2,0),
	"USADO" VARCHAR2(1),
	"FOLIO" NUMBER(7,0) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_ALUMNO_RES" 
   (	"PLANTEL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_SEP" VARCHAR2(20),
	"CICLO" NUMBER(2,0),
	"CURP" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"PATERNO" VARCHAR2(70),
	"MATERNO" VARCHAR2(70),
	"FECHA" DATE NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_UM" VARCHAR2(40),
	"GENERO" VARCHAR2(1),
	"EDAD" NUMBER(4,0),
	"GRADO" NUMBER(2,0),
	"PAIS_ID" NUMBER(3,0),
	"ESTADO_ID" NUMBER(3,0),
	"PREPA_LUGAR" NUMBER(2,0),
	"USADO" VARCHAR2(1),
	"FOLIO" NUMBER(7,0) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_ALUMNO_TRASPASO" 
   ("PLANTEL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_SEP" VARCHAR2(20),
	"CICLO" NUMBER(2,0),
	"CURP" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"PATERNO" VARCHAR2(70),
	"MATERNO" VARCHAR2(70),
	"CODIGO_PERSONAL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_UM" VARCHAR2(400),
	"GENERO" VARCHAR2(1),
	"EDAD" NUMBER(4,0),
	"GRADO" NUMBER(2,0),
	"PAIS_ID" NUMBER(3,0),
	"ESTADO_ID" NUMBER(3,0),
	"PREPA_LUGAR" NUMBER(2,0),
	"USADO" VARCHAR2(1),
	"FOLIO" NUMBER(7,0) NOT NULL ENABLE,
	"FECHA" VARCHAR2(10) DEFAULT '17/05/2021' NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_DOCENTES" 
   ("FOLIO" NUMBER(2,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) DEFAULT '-' NOT NULL ENABLE,
	"ESTUDIOS" VARCHAR2(1),
	"GENERO" VARCHAR2(1),
	"TEC" VARCHAR2(1),
	"LIC" VARCHAR2(1),
	"ESP" VARCHAR2(1),
	"MAE" VARCHAR2(1),
	"DOC" VARCHAR2(1),
	"TIEMPO" VARCHAR2(1),
	"ENLINEA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	CONSTRAINT "SEP_DOCENTES_PK" PRIMARY KEY ("FOLIO") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_DOCENTE2" 
   ("FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) NOT NULL ENABLE,
	"ESTUDIOS" VARCHAR2(1),
	"GENERO" VARCHAR2(1),
	"TEC" VARCHAR2(1),
	"LIC" VARCHAR2(1),
	"ESP" VARCHAR2(1),
	"MAE" VARCHAR2(1),
	"DOC" VARCHAR2(1),
	"TIEMPO" VARCHAR2(1),
	"ENLINEA" VARCHAR2(1) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_DOCENTE3" 
   ("FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) NOT NULL ENABLE,
	"ESTUDIOS" VARCHAR2(1),
	"GENERO" VARCHAR2(1),
	"TEC" VARCHAR2(1),
	"LIC" VARCHAR2(1),
	"ESP" VARCHAR2(1),
	"MAE" VARCHAR2(1),
	"DOC" VARCHAR2(1),
	"TIEMPO" VARCHAR2(1),
	"ENLINEA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_DOCENTE4" 
   ("FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) NOT NULL ENABLE,
	"ESTUDIOS" VARCHAR2(1),
	"GENERO" VARCHAR2(1),
	"TEC" VARCHAR2(1),
	"LIC" VARCHAR2(1),
	"ESP" VARCHAR2(1),
	"MAE" VARCHAR2(1),
	"DOC" VARCHAR2(1),
	"TIEMPO" VARCHAR2(1),
	"ENLINEA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_DOCENTE5" 
   ("FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) NOT NULL ENABLE,
	"ESTUDIOS" VARCHAR2(1),
	"GENERO" VARCHAR2(1),
	"TEC" VARCHAR2(1),
	"LIC" VARCHAR2(1),
	"ESP" VARCHAR2(1),
	"MAE" VARCHAR2(1),
	"DOC" VARCHAR2(1),
	"TIEMPO" VARCHAR2(1),
	"ENLINEA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."SEP_DOCENTE6" 
   (	"FOLIO" NUMBER(3,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70) NOT NULL ENABLE,
	"ESTUDIOS" VARCHAR2(1),
	"GENERO" VARCHAR2(1),
	"TEC" VARCHAR2(1),
	"LIC" VARCHAR2(1),
	"ESP" VARCHAR2(1),
	"MAE" VARCHAR2(1),
	"DOC" VARCHAR2(1),
	"TIEMPO" VARCHAR2(1),
	"ENLINEA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."SER_USUARIO" 
   ("USUARIO_ID" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(40) DEFAULT '-' NOT NULL ENABLE,
	"PATERNO" VARCHAR2(70) DEFAULT '-' NOT NULL ENABLE,
	"MATERNO" VARCHAR2(70) DEFAULT ' ',
	"CUENTA" VARCHAR2(20),
	"PASSWORD" VARCHAR2(100),
	"ROLES" VARCHAR2(100) DEFAULT 'ROLE_USER',
	CONSTRAINT "SER_USUARIO_PK" PRIMARY KEY ("USUARIO_ID") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."TEMP_CARRERA" 
   ("TIPO" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"CARRERA_ID" VARCHAR2(5) DEFAULT '0' NOT NULL ENABLE,
	"EJERCICIO_ID" VARCHAR2(8) DEFAULT '001-2022' NOT NULL ENABLE,
	CONSTRAINT "TEMP_CARRERA_PK" PRIMARY KEY ("TIPO","CARRERA_ID","EJERCICIO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."TEMP_CICLO" 
   ("CODIGO" VARCHAR2(20) NOT NULL ENABLE,
	"CICLO" VARCHAR2(20) DEFAULT '0' NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."TEMP_DOS" 
   (	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	CONSTRAINT "TEMP_DOS_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."TEMP_UNO" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE
   );
   
     CREATE TABLE "ENOC"."TIT_ANTECEDENTE2" 
   (	"FOLIO" NUMBER(7,0) NOT NULL ENABLE,
	"INSTITUCION" VARCHAR2(100),
	"ESTUDIOID" NUMBER(2,0),
	"ESTUDIO" VARCHAR2(100),
	"ENTIDADID" VARCHAR2(2),
	"ENTIDAD" VARCHAR2(100),
	"FECHAINICIO" DATE,
	"FECHATERMINACION" DATE,
	"CEDULA" VARCHAR2(8)
   );
   
     CREATE TABLE "ENOC"."TIT_CADENA" 
   ("FOLIO" VARCHAR2(20) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CADENA" VARCHAR2(2000) DEFAULT 'CADENA-ORIGINAL',
	"SELLO" VARCHAR2(2000) DEFAULT 'SELLO',
	"CADENA_SEP" VARCHAR2(2000),
	CONSTRAINT "TIT_CADENA_PK" PRIMARY KEY ("FOLIO","CODIGO_PERSONAL") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."TIT_CARRERA2" 
   (	"CVECARRERA" VARCHAR2(7) NOT NULL ENABLE,
	"NOMBRECARRERA" VARCHAR2(100),
	"FECHAINICIO" DATE,
	"FECHATERMINACION" DATE,
	"IDAUTORIZACION" NUMBER(2,0),
	"AUTORIZACION" VARCHAR2(50),
	"NUMERORVOE" VARCHAR2(100),
	"FOLIO" NUMBER(7,0) NOT NULL ENABLE
   );
   
   
     CREATE TABLE "ENOC"."TIT_EXPEDICION2" 
   ("FOLIO" NUMBER(7,0) NOT NULL ENABLE,
	"FECHAEXPEDICION" DATE,
	"MODALIDADID" NUMBER(2,0),
	"MODALIDAD" VARCHAR2(40),
	"FECHAEXAMEN" DATE,
	"FECHAEXENCION" DATE,
	"SERVICIO" NUMBER(1,0),
	"FUNDAMENTOID" NUMBER(2,0),
	"FUNDAMENTO" VARCHAR2(150) NOT NULL ENABLE,
	"ENTIDADID" VARCHAR2(2),
	"ENTIDAD" VARCHAR2(70)
   );
   
   
     CREATE TABLE "ENOC"."TIT_FIRMA_RES" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70),
	"PRIMERAPELLIDO" VARCHAR2(70),
	"SEGUNDOAPELLIDO" VARCHAR2(70),
	"CURP" VARCHAR2(18),
	"IDCARGO" NUMBER(2,0),
	"CARGO" VARCHAR2(50),
	"ABRTITULO" VARCHAR2(10),
	"SELLO" VARCHAR2(100),
	"CERTIFICADO" VARCHAR2(3000),
	"NUMEROCERTIFICADO" VARCHAR2(30),
	"INSTITUCION" VARCHAR2(10) NOT NULL ENABLE,
	"CER" BLOB
   );
   
   
     CREATE TABLE "ENOC"."TIT_INSTITUCION_USUARIO" 
   ("INSTITUCION" VARCHAR2(10) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(7) NOT NULL ENABLE,
	CONSTRAINT "TIT_INSTITUCION_USUARIO_PK" PRIMARY KEY ("INSTITUCION","USUARIO") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."TIT_PROFESIONAL2" 
   ("FOLIO" VARCHAR2(20) NOT NULL ENABLE,
	"CURP" VARCHAR2(18) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(70),
	"PRIMERAPELLIDO" VARCHAR2(70),
	"SEGUNDOAPELLIDO" VARCHAR2(70),
	"CORREOELECTRONICO" VARCHAR2(100)
   );
   
     CREATE TABLE "ENOC"."TMP" 
   ("CODIGO_PERSONAL" VARCHAR2(7),
	CONSTRAINT "TMP_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
     CREATE TABLE "ENOC"."USUARIO_PARAMETROS" 
   ("CODIGO_PERSONAL" CHAR(7) NOT NULL ENABLE,
	"CARGAS" VARCHAR2(150),
	"MODALIDADES" VARCHAR2(100),
	"F_INICIO" DATE,
	"F_FINAL" DATE,
	CONSTRAINT "USUARIO_PARAMETROS_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE
   );
   
     CREATE TABLE "ENOC"."VAL_DOCUMENTO" 
   ("CLAVE" VARCHAR2(100) NOT NULL ENABLE,
	"TIPO" VARCHAR2(20),
	"FOLIO" VARCHAR2(20),
	"CODIGO_PERSONAL" VARCHAR2(7),
	CONSTRAINT "VAL_DOCUMENTO_PK" PRIMARY KEY ("CLAVE") ENABLE
   );
   
   
     CREATE TABLE "ENOC"."VIG_DOC" 
   ("DOCUMENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"DOCUMENTO_NOMBRE" VARCHAR2(40) DEFAULT '-',
	"CORTO" VARCHAR2(20) DEFAULT '-' NOT NULL ENABLE,
	CONSTRAINT "VIG_DOC_PK" PRIMARY KEY ("DOCUMENTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."VIG_DOCAUTO" 
   ("AUTO_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"DOCUMENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"VIGENCIA" DATE,
	"COMENTARIO" VARCHAR2(300) DEFAULT '-' NOT NULL ENABLE,
	CONSTRAINT "VIG_DOCAUTO_PK" PRIMARY KEY ("AUTO_ID","DOCUMENTO_ID") ENABLE
   );
   
     CREATE TABLE "ENOC"."VIG_DOCUMENTO" 
   ("AUTO_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"DOCUMENTO_ID" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVO" BLOB,
	"NOMBRE" VARCHAR2(70) DEFAULT '-' NOT NULL ENABLE,
	"HOJA" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	CONSTRAINT "VIG_DOCUMENTO_PK" PRIMARY KEY ("AUTO_ID","DOCUMENTO_ID","HOJA") ENABLE
   );
   
     CREATE TABLE "ENOC"."VOTO_ALUMNO_RES" 
   ("CODIGO_PERSONAL" VARCHAR2(7) NOT NULL ENABLE,
	"CANDIDATO_ID" NUMBER(5,0) NOT NULL ENABLE,
	"VOTO" VARCHAR2(7) NOT NULL ENABLE,
	"EVENTO_ID" NUMBER(4,0) NOT NULL ENABLE,
	"FECHA" TIMESTAMP(6)
   );
   
     CREATE TABLE "ENOC"."VOTO_CANDIDATO_ALUMNO" 
   ("EVENTO_ID" NUMBER(4,0) NOT NULL ENABLE,
	"CANDIDATO_ID" NUMBER(2,0) NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(7) DEFAULT '0' NOT NULL ENABLE,
	"FACULTAD_ID" VARCHAR2(3) DEFAULT '000',
	"ORDEN" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	CONSTRAINT "VOTO_CANDIDATO_ALUMNO_PK" PRIMARY KEY ("EVENTO_ID","CANDIDATO_ID","CODIGO_PERSONAL") ENABLE
   );