ALTER TABLE "ENOC"."ACCESO" MODIFY ("CLAVE" VARCHAR2(100));
ALTER TABLE "ENOC"."ACCESO_CLAVE" MODIFY ("CLAVE" VARCHAR2(100));
ALTER TABLE "ENOC"."ALUM_ACADEMICO" MODIFY ("CLAS_FIN" NUMBER(2,0) DEFAULT 1);
ALTER TABLE "ENOC"."ALUM_DIRECCION" DROP CONSTRAINT "FK8BBA1BF4423DFF70";
ALTER TABLE "ENOC"."ALUM_GRADUA" MODIFY ("DIPLOMA" VARCHAR2(150));
ALTER TABLE "ENOC"."ALUM_PERSONAL" MODIFY ("BAUTIZADO" CHAR(1) DEFAULT 'S');
/*ALTER TABLE "ENOC"."ALUM_PLAN" MODIFY ("PLAN_ID" CHAR(8));*/
ALTER TABLE "ENOC"."ALUM_PLAN2" DROP ("CICLO_SEP");
ALTER TABLE "ENOC"."ALUM_PLAN2" DROP ("PLAN_TEMP");
ALTER TABLE "ENOC"."APFISICA_GRUPO" MODIFY ("HORA" VARCHAR2(20));
ALTER TABLE "ENOC"."BAJA_ALUMNO" MODIFY ("COMENTARIO" VARCHAR2(500));
ALTER TABLE "ENOC"."BEC_ACUERDO" DROP CONSTRAINT "FKFE593C4C55E332BE";
ALTER TABLE "ENOC"."BEC_INFORME_ALUMNO" DROP CONSTRAINT "FK99B56E2655E332BE";
DROP TABLE "ENOC"."BEC_PLAZAS2";
CREATE TABLE "ENOC"."BEC_PLAZAS2" 
("ID_EJERCICIO" VARCHAR2(8) NOT NULL ENABLE,
"ID_CCOSTO" VARCHAR2(20) NOT NULL ENABLE,
"NUM_PLAZAS" NUMBER(3,0),
"NUM_TEMPORALES" NUMBER(3,0),
"NUM_INDUSTRIALES" NUMBER(3,0),
"NUM_PREINDUSTRIALES" NUMBER(3,0),
"NUM_POSGRADO" NUMBER(3,0),
"PERIODO_ID" VARCHAR2(5) NOT NULL ENABLE,
"CONTACTO" VARCHAR2(100) NOT NULL ENABLE,
"TELEFONO" VARCHAR2(40) NOT NULL ENABLE,
"CORREO" VARCHAR2(100) NOT NULL ENABLE
);
DROP TABLE "ENOC"."BEC_TIPO2";
CREATE TABLE "ENOC"."BEC_TIPO2"(
    "ID_EJERCICIO" VARCHAR2(8) NOT NULL ENABLE,
	"TIPO" NUMBER(2,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"DEPARTAMENTOS" VARCHAR2(500),
	"CUENTA" VARCHAR2(40),
	"PORCENTAJE" VARCHAR2(3),
	"MESES" VARCHAR2(30),
	"HORAS" NUMBER(4,0),
	"HORAS_PREPA" NUMBER(4,0),
	"ACUERDO" VARCHAR2(1),
	"IMPORTE" NUMBER(8,2),
	"TIPO_ALUMNO" VARCHAR2(50),
	"DIEZMO" VARCHAR2(1),
	"ESTADO" VARCHAR2(2),
	"ACUMULA" VARCHAR2(1),
	"COLPORTA" VARCHAR2(1),
	"APLICA_ADICIONAL" VARCHAR2(1) NOT NULL ENABLE,
	"MAXIMO" NUMBER(5,2) NOT NULL ENABLE,
	"LIMITE" NUMBER(10,2),
	"CUENTA_SUNPLUS" VARCHAR2(20) NOT NULL ENABLE,
	"FLAG" VARCHAR2(20)
);
ALTER TABLE "ENOC"."BIT_ETIQUETA" MODIFY ("COMENTARIO" VARCHAR2(2000));
ALTER TABLE "ENOC"."BIT_TRAMITE" MODIFY ("MAXIMO" NUMBER(6,2));
ALTER TABLE "ENOC"."BIT_TRAMITE" MODIFY ("MINIMO" NUMBER(6,2));
ALTER TABLE "ENOC"."BIT_TRAMITE" MODIFY ("PROMEDIO" NUMBER(6,2));
/*ALTER TABLE "ENOC"."BIT_TRAMITE" MODIFY ("REQUISITOS" CLOB DEFAULT '-');*/
ALTER TABLE "ENOC"."BIT_TRAMITE_ALUMNO" MODIFY ("COMENTARIO" VARCHAR2(770));
ALTER TABLE "ENOC"."CANCELA_ESTUDIO" MODIFY ("COMENTARIO" VARCHAR2(777));
ALTER TABLE "ENOC"."CAND_TIPO" MODIFY ("TELEFONO" VARCHAR2(30));
ALTER TABLE "ENOC"."CAT_NIVEL" DROP ("INTERAMERICA");
ALTER TABLE "ENOC"."CERT_ALUM_NOTA" MODIFY ("NOTA" VARCHAR2(5));
ALTER TABLE "ENOC"."CERT_ALUM_NOTA" MODIFY ("NOTA_LETRA" VARCHAR2(30));
ALTER TABLE "ENOC"."COND_REPORTE" ADD CONSTRAINT "COND_REPORTE_PK" PRIMARY KEY ("IDREPORTE") ENABLE;
ALTER TABLE "ENOC"."CONV_EVENTO" MODIFY ("DICTAMEN" VARCHAR2(70) DEFAULT '-');
ALTER TABLE "ENOC"."EDO" MODIFY ("MODALIDAD" VARCHAR2(100) DEFAULT '-0-');
ALTER TABLE "ENOC"."EDO_ALUMNOPREG" MODIFY ("TIPO" VARCHAR2(1));

/*ALTER TABLE "ENOC"."EDO_ALUMNOPREG" DROP CONSTRAINT "EDO_ALUMNOPREG_PK";*/
/*ALTER TABLE "ENOC"."EDO_ALUMNOPREG" ADD CONSTRAINT "EDO_ALUMNOPREG_PK" PRIMARY KEY ("EDO_ID","PREGUNTA_ID") ENABLE;*/
ALTER TABLE "ENOC"."EDO_ALUMNORESP" MODIFY ("RESPUESTA" VARCHAR2(250) DEFAULT '0');
ALTER TABLE "ENOC"."EDO_ALUMNORESP" MODIFY ("RESPUESTA" NOT NULL ENABLE);
ALTER TABLE "ENOC"."EDO_ALUMNORESP" DROP CONSTRAINT "EDO_ALUMNORESP_R01";
ALTER TABLE "ENOC"."EDO_ALUMNORESP" ADD CONSTRAINT "EDO_ALUMNORESP_R01" FOREIGN KEY ("EDO_ID","PREGUNTA_ID") REFERENCES "ENOC"."EDO_ALUMNOPREG"("EDO_ID","PREGUNTA_ID") ENABLE;
ALTER TABLE "ENOC"."EMP_HORAS" MODIFY ("FRECUENCIA" NUMBER(4,2) DEFAULT 0);
ALTER TABLE "ENOC"."EMP_MAESTRO" DROP ("CURP");
ALTER TABLE "ENOC"."EXA_EGRESO" ADD CONSTRAINT "EXA_EGRESO_PK" PRIMARY KEY ("EGRESO_ID") ENABLE;
ALTER TABLE "ENOC"."FIN_ROLES" MODIFY ("ASESOR" VARCHAR2(200));
ALTER TABLE "ENOC"."HCA_MAESTRO" MODIFY ("CARRERA_ID" VARCHAR2(5));
ALTER TABLE "ENOC"."INT_ACCESO" MODIFY ("CODIGO_PERSONAL" NOT NULL ENABLE);
ALTER TABLE "ENOC"."INT_ACCESO" MODIFY ("DORMITORIO_ID" NOT NULL ENABLE);
DELETE FROM ENOC.INT_ACCESO WHERE CODIGO_PERSONAL LIKE '%107011%' AND ROL = 'M';
ALTER TABLE "ENOC"."INT_ACCESO" ADD CONSTRAINT "INT_ACCESO_PK" PRIMARY KEY ("CODIGO_PERSONAL") ENABLE;
ALTER TABLE "ENOC"."INT_ALUMNO" MODIFY ("CODIGO_PERSONAL" NOT NULL ENABLE);
ALTER TABLE "ENOC"."INT_ALUMNO" MODIFY ("CUARTO_ID" NOT NULL ENABLE);
ALTER TABLE "ENOC"."INT_ALUMNO" MODIFY ("DORMITORIO_ID" NOT NULL ENABLE);
ALTER TABLE "ENOC"."INT_ALUMNO" ADD CONSTRAINT "INT_ALUMNO_PK" PRIMARY KEY ("CUARTO_ID","CODIGO_PERSONAL","DORMITORIO_ID") ENABLE;
ALTER TABLE "ENOC"."INT_CUARTO" MODIFY ("PASILLO" NOT NULL ENABLE);
ALTER TABLE "ENOC"."INT_CUARTO" ADD CONSTRAINT "INT_CUARTO_PK" PRIMARY KEY ("DORMITORIO_ID","CUARTO_ID") ENABLE;
ALTER TABLE "ENOC"."INV_ARCHIVO" MODIFY ("NOMBRE" VARCHAR2(250));
ALTER TABLE "ENOC"."INV_PROYECTO" MODIFY ("INVESTIGADORES" VARCHAR2(300) DEFAULT '-');
ALTER TABLE "ENOC"."INV_RESULTADO" MODIFY ("BIBLIOGRAFIA" NOT NULL ENABLE);
ALTER TABLE "ENOC"."KRDX_CURSO_IMP" MODIFY ("NOTA1" NUMBER(3,0) DEFAULT 0);
ALTER TABLE "ENOC"."KRDX_CURSO_IMP" MODIFY ("NOTA2" NUMBER(3,0) DEFAULT 0);
DELETE FROM ENOC.MAPA_NUEVO_PLAN WHERE PLAN_ID = 'LCED2011' AND VERSION_ID > 1;
ALTER TABLE "ENOC"."MAPA_NUEVO_PLAN" ADD CONSTRAINT "PK_MNP" PRIMARY KEY ("PLAN_ID") ENABLE;
ALTER TABLE "ENOC"."MAPA_NUEVO_CURSO" ADD CONSTRAINT "FK_MAPA_NUEVO_PLAN" FOREIGN KEY ("PLAN_ID") REFERENCES "ENOC"."MAPA_NUEVO_PLAN"("PLAN_ID") ENABLE;
ALTER TABLE "ENOC"."MENT_ALUMNO" MODIFY ("CARGA_ID" NOT NULL ENABLE);
ALTER TABLE "ENOC"."PRON_BIBLIO" MODIFY ("BIBLIO_NOMBRE" VARCHAR2(900) DEFAULT '-');
ALTER TABLE "ENOC"."PRON_ESQUEMA" MODIFY ("ESTRATEGIA_NOMBRE" VARCHAR2(250) DEFAULT '-');
ALTER TABLE "ENOC"."PRON_MATERIA" MODIFY ("CORREO" VARCHAR2(200) DEFAULT '-');
ALTER TABLE "ENOC"."PRON_MATERIA" MODIFY ("ESPECIAL" VARCHAR2(1990) DEFAULT '-');
ALTER TABLE "ENOC"."PRON_MATERIA" MODIFY ("FORMACION" VARCHAR2(250) DEFAULT '-');
ALTER TABLE "ENOC"."PRON_MATERIA" MODIFY ("INTEGRIDAD" VARCHAR2(1990) DEFAULT '-');
ALTER TABLE "ENOC"."RES_DATOS" MODIFY ("TEL_NUMERO" VARCHAR2(14));
ALTER TABLE "ENOC"."RES_DATOS" MODIFY ("TUT_APELLIDOS" VARCHAR2(40));
ALTER TABLE "ENOC"."RES_DATOS" MODIFY ("TUT_NOMBRE" VARCHAR2(30));
ALTER TABLE "ENOC"."RES_DATOS" DROP CONSTRAINT "PK_RESALUMNO";
ALTER TABLE "ENOC"."RES_RAZONES" MODIFY ("DESCRIPCION" VARCHAR2(40));
ALTER TABLE "ENOC"."ROT_ESPECIALIDAD" MODIFY ("CURSO_ID" CHAR(15));
ALTER TABLE "ENOC"."SAL_AUTO" MODIFY ("POLIZA" VARCHAR2(30) DEFAULT '-');
ALTER TABLE "ENOC"."SAL_INVITADO" MODIFY ("NOMBRE" VARCHAR2(100) DEFAULT '-');
ALTER TABLE "ENOC"."SAL_SOLICITUD" DROP ("PROPOSITO");
ALTER TABLE "ENOC"."SAL_SOLICITUD" MODIFY ("FOLIO" VARCHAR2(10));
DROP TABLE "ENOC"."SEP_ALUMNO";
  CREATE TABLE "ENOC"."SEP_ALUMNO" 
   (	"PLANTEL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_SEP" VARCHAR2(20),
	"CICLO" NUMBER(2,0),
	"CURP" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"PATERNO" VARCHAR2(70),
	"MATERNO" VARCHAR2(70),
	"FECHA" DATE NOT NULL ENABLE,
	"CODIGO_PERSONAL" VARCHAR2(20) NOT NULL ENABLE,
	"PLAN_UM" VARCHAR2(40),
	"GENERO" VARCHAR2(1) DEFAULT '-',
	"EDAD" NUMBER(4,0),
	"GRADO" NUMBER(2,0) DEFAULT 0,
	"PAIS_ID" NUMBER(3,0) DEFAULT 0,
	"ESTADO_ID" NUMBER(3,0) DEFAULT 0,
	"PREPA_LUGAR" NUMBER(2,0) DEFAULT 0,
	"USADO" VARCHAR2(1) DEFAULT 'N',
	"FOLIO" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE,
	CONSTRAINT "SEP_ALUMNO_PK" PRIMARY KEY ("FOLIO") ENABLE
);
ALTER TABLE "ENOC"."SEP_TEMP" DROP ("PLANTEL");
ALTER TABLE "ENOC"."SEP_TEMP" DROP ("PLAN_ID");
ALTER TABLE "ENOC"."SSOC_ASIGNACION" MODIFY ("DEPENDENCIA" VARCHAR2(120));
ALTER TABLE "ENOC"."SSOC_ASIGNACION" MODIFY ("SECTOR" NULL);
ALTER TABLE "ENOC"."SSOC_DOCUMENTOS" MODIFY ("ACCESO" VARCHAR2(1) DEFAULT 'A');
ALTER TABLE "ENOC"."SSOC_REQUISITOS" MODIFY ("REQUISITO_NOMBRE" VARCHAR2(1900));

ALTER TABLE ENOC.SSOC_SECTOR ADD ID NUMBER(2) DEFAULT 0 NOT NULL;
UPDATE ENOC.SSOC_SECTOR SET ID = TO_NUMBER(SECTOR_ID);
ALTER TABLE ENOC.SSOC_SECTOR DROP COLUMN SECTOR_ID;
ALTER TABLE ENOC.SSOC_SECTOR ADD SECTOR_ID NUMBER(2) DEFAULT 0 NOT NULL;
UPDATE ENOC.SSOC_SECTOR SET SECTOR_ID = ID;
ALTER TABLE ENOC.SSOC_SECTOR DROP COLUMN ID;
ALTER TABLE ENOC.SSOC_SECTOR ADD CONSTRAINT PK_SSOC_SECTOR PRIMARY KEY (SECTOR_ID);
ALTER TABLE "ENOC"."TIT_ALUMNO" DROP ("CADENA");
ALTER TABLE "ENOC"."TIT_ANTECEDENTE" MODIFY ("INSTITUCION" VARCHAR2(200));
ALTER TABLE "ENOC"."TIT_CARGO" MODIFY ("CARGO_NOMBRE" VARCHAR2(70));
ALTER TABLE "ENOC"."VIG_AUTO" DROP ("ALUMNO");
ALTER TABLE "ENOC"."VIG_AUTO" DROP ("EMPLEADO");
ALTER TABLE "ENOC"."VIG_AUTO" DROP ("OTRO");
ALTER TABLE "ENOC"."VIG_AUTO" DROP ("SERIE");
ALTER TABLE ENOC.PRON_MATERIA MODIFY (ESPECIAL VARCHAR2(1990) DEFAULT '-');