CREATE OR REPLACE FORCE VIEW "ENOC"."ALUMNO"
 ( "CODIGO_PERSONAL", "NOMBRE", "APELLIDO_PATERNO", "APELLIDO_MATERNO", "NOMBRE_LEGAL", "COTEJADO", "F_NACIMIENTO", "SEXO", "ESTADO_CIVIL", "RELIGION_ID", "PAIS_ID", "ESTADO_ID", "CIUDAD_ID", "NACIONALIDAD", "CURP", "MODALIDAD_ID", "CLAS_FIN", "RESIDENCIA_ID", "PLAN_ID", "CARRERA_ID", "CORREO", "TELEFONO"
  )  AS
SELECT
    A.CODIGO_PERSONAL,
    A.NOMBRE,
    A.APELLIDO_PATERNO,
    A.APELLIDO_MATERNO,
    A.NOMBRE_LEGAL,
    A.COTEJADO,
    A.F_NACIMIENTO,
    A.SEXO,
    A.ESTADO_CIVIL,
    A.RELIGION_ID,
    A.PAIS_ID,
    A.ESTADO_ID,
    A.CIUDAD_ID,
    A.NACIONALIDAD,
    A.CURP,
    B.MODALIDAD_ID,
    B.CLAS_FIN,
    B.RESIDENCIA_ID,
    ALUM_PLAN_ID(B.CODIGO_PERSONAL),
    ALUM_CARRERA_ID(B.CODIGO_PERSONAL),
    A.EMAIL,
    A.TELEFONO
FROM ALUM_PERSONAL A, ALUM_ACADEMICO B
WHERE B.CODIGO_PERSONAL = A.CODIGO_PERSONAL
  AND A.CODIGO_PERSONAL NOT LIKE '98%';

CREATE OR REPLACE FORCE VIEW "ENOC"."ALUMNO_CURSO"
 ( "CODIGO_PERSONAL", "CARGA_ID", "BLOQUE_ID", "CURSO_CARGA_ID", "CARRERA_ID", "MODALIDAD_ID", "PLAN_ID", "CURSO_ID", "NOMBRE_CURSO", "CICLO", "CREDITOS", "HT", "HP", "NOTA_APROBATORIA", "CURSO_ID2", "NOMBRE_CURSO2", "CREDITOS2", "HT2", "HP2", "NOTA", "F_EVALUACION", "TIPOCAL_ID", "NOTA_EXTRA", "F_EXTRA", "CONVALIDACION", "TITULO", "F_TITULO", "GRUPO", "MAESTRO", "ESTADO", "CORRECCION", "LLAVE", "OPTATIVA", "NOTA_CONVA"
  )  AS
SELECT
    A.CODIGO_PERSONAL,
    '000000',
    0,
    '000000-0000',
    CARRERA(SUBSTR(A.CURSO_ID,1,8)),
    1,
    B.PLAN_ID,
    A.CURSO_ID,
    B.NOMBRE_CURSO,
    B.CICLO,
    B.CREDITOS,
    B.HT,
    B.HP,
    B.NOTA_APROBATORIA,
    A.CURSO_ID2,
    C.NOMBRE_CURSO,
    C.CREDITOS,
    C.HT,
    C.HP,
    NVL(A.NOTA,0),
    A.F_CREADA,
    A.TIPOCAL_ID,
    NVL(A.NOTA_EXTRA,0),
    A.F_EXTRA,
    A.CONVALIDACION,
    A.TITULO,
    DECODE(A.TITULO,'S',A.F_CREADA,NULL),
    '@',
    '9800000',
    'I',
    'N',
    CODIGO_PERSONAL||'-'||TRIM(TO_CHAR(FOLIO,'000')),
    A.OPTATIVA_NOMBRE,
    A.NOTA_CONVA
FROM
    KRDX_CURSO_IMP A,
    (
        SELECT
            PLAN_ID,
            CURSO_ID,
            NOMBRE_CURSO,
            CICLO,
            CREDITOS,
            CASE HT WHEN 0 THEN HFD ELSE HT END AS HT,
            HP,
            NOTA_APROBATORIA
        FROM
            MAPA_CURSO
    )
        B,
    (
        SELECT
            CURSO_ID,
            NOMBRE_CURSO,
            CREDITOS,
            CASE HT WHEN 0 THEN HFD ELSE HT END AS HT,
            HP
        FROM
            MAPA_CURSO
    )
        C
WHERE
        B.CURSO_ID = A.CURSO_ID
  AND C.CURSO_ID = A.CURSO_ID2

UNION

SELECT
    A.CODIGO_PERSONAL,
    SUBSTR(A.CURSO_CARGA_ID,1,6),
    B.BLOQUE_ID,
    A.CURSO_CARGA_ID,
    CARRERA(SUBSTR(A.CURSO_ID,1,8)),
    B.MODALIDAD_ID,
    C.PLAN_ID,
    C.CURSO_ID,
    C.NOMBRE_CURSO,
    C.CICLO,
    C.CREDITOS,
    C.HT,
    C.HP,
    C.NOTA_APROBATORIA,
    A.CURSO_ID2,
    D.NOMBRE_CURSO,
    D.CREDITOS,
    D.HT,
    D.HP,
    NVL(A.NOTA,0),
    A.F_NOTA,
    A.TIPOCAL_ID,
    NVL(A.NOTA_EXTRA,0),
    A.F_EXTRA,
    'N',
    A.TITULO,
    A.F_TITULO,
    B.GRUPO,
    B.CODIGO_PERSONAL,
    B.ESTADO,
    A.CORRECCION,
    A.CODIGO_PERSONAL||A.CURSO_CARGA_ID||A.CURSO_ID,
    GRUPO_OPTATIVA(A.CURSO_CARGA_ID),
    '-'
FROM
    KRDX_CURSO_ACT A,
    CARGA_GRUPO B,
    (
        SELECT
            PLAN_ID,
            CURSO_ID,
            NOMBRE_CURSO,
            CICLO,
            CREDITOS,
            CASE HT WHEN 0 THEN HFD ELSE HT END AS HT,
            HP,
            NOTA_APROBATORIA
        FROM
            MAPA_CURSO
    )
        C,
    (
        SELECT
            CURSO_ID,
            NOMBRE_CURSO,
            CREDITOS,
            CASE HT WHEN 0 THEN HFD ELSE HT END AS HT,
            HP,
            NOTA_APROBATORIA
        FROM
            MAPA_CURSO
    )
        D
WHERE
        B.CURSO_CARGA_ID = A.CURSO_CARGA_ID
  AND C.CURSO_ID = A.CURSO_ID
  AND D.CURSO_ID = A.CURSO_ID2;

CREATE OR REPLACE FORCE VIEW "ENOC"."ALUMNO_EFICIENCIA"
 ( "CODIGO_PERSONAL", "CURSO_CARGA_ID", "EVALUACION_ID", "TIPO", "VALOR", "NOTA", "EVALUADAS", "PUNTOS", "TOT_ACTIVIDADES"
  )  AS
SELECT
    KAE.CODIGO_PERSONAL,
    KAE.CURSO_CARGA_ID,
    KAE.EVALUACION_ID,
    CGE.TIPO,
    CGE.VALOR,
    NOTA,
    CASE WHEN KAE.EVALUADAS = 0 AND KAE.TOT_ACTIVIDADES = 0 AND NOTA IS NOT NULL THEN 100 ELSE KAE.EVALUADAS END,
    KAE.PUNTOS,
    KAE.TOT_ACTIVIDADES
FROM KRDX_ALUMNO_EVAL KAE, CARGA_GRUPO_EVALUACION CGE
WHERE CGE.CURSO_CARGA_ID = KAE.CURSO_CARGA_ID
  AND CGE.EVALUACION_ID = KAE.EVALUACION_ID;

CREATE OR REPLACE FORCE VIEW "ENOC"."ALUM_CARGAMATERIAS"
 ( "CODIGO_PERSONAL", "PLAN_ID", "CARGA_ID", "BLOQUE_ID", "CURSO_CARGA_ID", "CURSO_ID", "NOMBRE_CURSO", "CICLO", "CREDITOS", "GRUPO", "CONDICION", "TIPO_CURSO", "FACULTADID", "FACULTAD", "CARRERAID", "CARRERA", "MODALIDAD_ID"
  )  AS
SELECT
    KCA.CODIGO_PERSONAL,
    MP.PLAN_ID,
    CG.CARGA_ID,
    CG.BLOQUE_ID,
    CGC.CURSO_CARGA_ID,
    MC.CURSO_ID,
    MC.NOMBRE_CURSO,
    MC.CICLO,
    MC.CREDITOS,
    CG.GRUPO,
    KCA.TIPOCAL_ID,
    MC.Tipocurso_id,
    CF.FACULTAD_ID,
    CF.NOMBRE_FACULTAD,
    CC.CARRERA_ID,
    CC.NOMBRE_CARRERA,
    CG.MODALIDAD_ID
FROM
    KRDX_CURSO_ACT KCA,
    CARGA_GRUPO_CURSO CGC,
    CARGA_GRUPO CG,
    MAPA_CURSO MC,
    MAPA_PLAN MP,
    CAT_CARRERA CC,
    CAT_FACULTAD CF
WHERE
        KCA.CURSO_CARGA_ID = CGC.CURSO_CARGA_ID
  AND CG.CURSO_CARGA_ID = CGC.CURSO_CARGA_ID
  AND MC.CURSO_ID = CGC.CURSO_ID
  AND MP.PLAN_ID = MC.PLAN_ID
  AND CC.CARRERA_ID = MP.CARRERA_ID
  AND CF.FACULTAD_ID = CC.FACULTAD_ID
  AND CGC.ORIGEN = 'O';

CREATE OR REPLACE FORCE VIEW "ENOC"."CARGA_ACADEMICA"
 ( "CURSO_CARGA_ID", "CARGA_ID", "BLOQUE_ID", "CODIGO_PERSONAL", "NOMBRE", "CARRERA_ID", "GRUPO", "MODALIDAD_ID", "ESTADO", "F_INICIO", "F_FINAL", "F_ENTREGA", "ORIGEN", "PLAN_ID", "CURSO_ID", "NOMBRE_CURSO", "CICLO", "CREDITOS", "HT", "HP", "HI", "NOTA_APROBATORIA", "HORARIO", "VALEUCAS", "NUM_ALUM", "SEMANAS", "OPTATIVA", "HH", "GRUPO_HORARIO", "SALON", "MODO", "CODIGO_OTRO"
  )  AS
SELECT A.CURSO_CARGA_ID,
       A.CARGA_ID,
       A.BLOQUE_ID,
       A.CODIGO_PERSONAL,
       EMP_APELLIDO(A.CODIGO_PERSONAL) NOMBRE,
       CARRERA(C.PLAN_ID),
       A.GRUPO,
       A.MODALIDAD_ID,
       A.ESTADO,
       A.F_INICIO,
       A.F_FINAL,
       A.F_ENTREGA,
       B.ORIGEN,
       C.PLAN_ID,
       C.CURSO_ID,
       C.NOMBRE_CURSO,
       C.CICLO,
       C.CREDITOS,
       C.HT,
       C.HP,
       C.HI,
       C.NOTA_APROBATORIA,
       C.HORARIO,
       A.VALEUCAS,
       A.NUM_ALUM,
       A.SEMANAS,
       A.OPTATIVA,
       C.HH,
       B.GRUPO_HORARIO,
       C.SALON,
       A.MODO,
       A.CODIGO_OTRO
FROM CARGA_GRUPO A,
     CARGA_GRUPO_CURSO B,
     MAPA_CURSO C
WHERE B.CURSO_CARGA_ID = A.CURSO_CARGA_ID
  AND C.CURSO_ID         = B.CURSO_ID;

CREATE OR REPLACE FORCE VIEW "ENOC"."CARGA_HORARIO"
 ( "CURSO_CARGA_ID", "SALON_ID", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FINAL", "MINUTO_FINAL", "HORARIO_ID", "PERIODO", "BLOQUE_ID", "FOLIO"
  )  AS
SELECT CGH.CURSO_CARGA_ID, CGH.SALON_ID, CGH.DIA, CHF.HORA_INICIO, CHF.MINUTO_INICIO, CHF.HORA_FINAL, CHF.MINUTO_FINAL, CGH.HORARIO_ID, CGH.PERIODO, CGH.BLOQUE_ID, CGH.FOLIO
FROM ENOC.CARGA_GRUPO_HORA CGH, ENOC.CAT_HORARIOFACULTAD CHF
WHERE CHF.HORARIO_ID = CGH.HORARIO_ID
  AND CHF.PERIODO = CGH.PERIODO;

CREATE OR REPLACE VIEW "ENOC"."MAESTRO_EVALUACION"
 ( "CURSO_CARGA_ID", "MAESTRO", "EVALUACION_ID", "NOMBRE_EVALUACION", "FECHA", "ESTRATEGIA_ID", "VALOR", "TIPO", "NUM_ALUMNOS", "NUM_ACT", "EVAL_EVAL", "ACT_EVAL"
  )  AS
SELECT CURSO_CARGA_ID, GRUPO_MAESTRO(CURSO_CARGA_ID) AS MAESTRO, EVALUACION_ID, NOMBRE_EVALUACION, FECHA, ESTRATEGIA_ID, VALOR, TIPO,
       ENOC.MATERIA_ALUMNOS(CURSO_CARGA_ID) AS NUM_ALUMNOS,
       (SELECT COUNT(ACTIVIDAD_ID) FROM ENOC.CARGA_GRUPO_ACTIVIDAD WHERE CURSO_CARGA_ID = CGE.CURSO_CARGA_ID AND EVALUACION_ID = CGE.EVALUACION_ID),
       (SELECT COUNT(EVALUACION_ID) FROM ENOC.KRDX_ALUMNO_EVAL WHERE CURSO_CARGA_ID = CGE.CURSO_CARGA_ID AND EVALUACION_ID = CGE.EVALUACION_ID),
       (SELECT COUNT(ACTIVIDAD_ID) FROM ENOC.KRDX_ALUMNO_ACTIV WHERE CURSO_CARGA_ID = CGE.CURSO_CARGA_ID AND EVALUACION_ID = CGE.EVALUACION_ID)
FROM CARGA_GRUPO_EVALUACION CGE;

CREATE OR REPLACE FORCE VIEW "ENOC"."MOD_OPCION"
 ( "MODULO_ID", "OPCION_ID", "NOMBRE_MODULO", "NOMBRE_OPCION", "URL_MODULO", "URL_OPCION", "USUARIOS", "CARPETA"
  )  AS
SELECT
    A.MODULO_ID,
    B.OPCION_ID,
    A.NOMBRE_MODULO,
    B.NOMBRE_OPCION,
    A.URL,
    B.URL,
    B.USUARIOS,
    B.CARPETA
FROM MODULO A, MODULO_OPCION B
WHERE B.MODULO_ID = A.MODULO_ID;

CREATE OR REPLACE FORCE VIEW "ENOC"."PLAN_CICLO"
 ( "PLAN_ID", "CICLO", "CREDITOS"
  )  AS
SELECT
    PLAN_ID,
    CICLO,
    CREDITOS_PLAN_CICLO(PLAN_ID, CICLO)
FROM MAPA_CURSO GROUP BY PLAN_ID, CICLO
ORDER BY 1,2
;