package aca.saii.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

public class SaiiDatosExtraMapper implements RowMapper<SaiiDatosExtra>{
	
	public SaiiDatosExtra mapRow(ResultSet rs, int arg1) throws SQLException {
		
		SaiiDatosExtra objeto = new SaiiDatosExtra();
		
		objeto.setPLAN_ID(rs.getString("PLAN_ID"));
		objeto.setPLAN_NOMBRE(rs.getString("PLAN_NOMBRE"));
		objeto.setFECHA(rs.getString("FECHA"));
		objeto.setDIS_N_ING(rs.getInt("DIS_N_ING"));
		objeto.setDIS_R_ING(rs.getInt("DIS_R_ING"));
		objeto.setDIS_TOTAL(rs.getInt("DIS_TOTAL"));
		objeto.setREG_ALUM_H(rs.getInt("REG_ALUM_H"));
		objeto.setREG_ALUM_M(rs.getInt("REG_ALUM_M"));
		objeto.setREG_ALUM_T(rs.getInt("REG_ALUM_T"));
		objeto.setCUR_REM_H(rs.getInt("CUR_REM_H"));
		objeto.setCUR_REM_M(rs.getInt("CUR_REM_M"));
		objeto.setCUR_REM_T(rs.getInt("CUR_REM_T"));
		objeto.setRET_SEG_H(rs.getInt("RET_SEG_H"));
		objeto.setRET_SEG_M(rs.getInt("RET_SEG_M"));
		objeto.setRET_SEG_T(rs.getInt("RET_SEG_T"));
		objeto.setDESERT_H(rs.getInt("DESERT_H"));
		objeto.setDESERT_M(rs.getInt("DESERT_M"));
		objeto.setDESERT_T(rs.getInt("DESERT_T"));
		objeto.setDESERT_19(rs.getInt("DESERT_19"));
		objeto.setDESERT_20_24(rs.getInt("DESERT_20_24"));
		objeto.setDESERT_25_29(rs.getInt("DESERT_25_29"));
		objeto.setDESERT_30(rs.getInt("DESERT_30"));
		objeto.setDESERT_DIS(rs.getInt("DESERT_DIS"));
		objeto.setTRAB_SIM_H(rs.getInt("TRAB_SIM_H"));
		objeto.setTRAB_SIM_M(rs.getInt("TRAB_SIM_M"));
		objeto.setTRAB_SIM_T(rs.getInt("TRAB_SIM_T"));
		objeto.setMOVIL_NAC_H(rs.getInt("MOVIL_NAC_H"));
		objeto.setMOVIL_NAC_M(rs.getInt("MOVIL_NAC_M"));
		objeto.setMOVIL_NAC_T(rs.getInt("MOVIL_NAC_T"));
		objeto.setMOVIL_NAC_19(rs.getInt("MOVIL_NAC_19"));
		objeto.setMOVIL_NAC_20_24(rs.getInt("MOVIL_NAC_20_24"));
		objeto.setMOVIL_NAC_25_29(rs.getInt("MOVIL_NAC_25_29"));
		objeto.setMOVIL_NAC_30(rs.getInt("MOVIL_NAC_30"));
		objeto.setMOVIL_NAC_DIS(rs.getInt("MOVIL_NAC_DIS"));
		objeto.setMOVIL_INT_H(rs.getInt("MOVIL_INT_H"));
		objeto.setMOVIL_INT_M(rs.getInt("MOVIL_INT_M"));
		objeto.setMOVIL_INT_T(rs.getInt("MOVIL_INT_T"));
		objeto.setMOVIL_INT_19(rs.getInt("MOVIL_INT_19"));
		objeto.setMOVIL_INT_20_24(rs.getInt("MOVIL_INT_20_24"));
		objeto.setMOVIL_INT_25_29(rs.getInt("MOVIL_INT_25_29"));
		objeto.setMOVIL_INT_30(rs.getInt("MOVIL_INT_30"));
		objeto.setMOVIL_INT_DIS(rs.getInt("MOVIL_INT_DIS"));
		objeto.setSERV_COM_H(rs.getInt("SERV_COM_H"));
		objeto.setSERV_COM_M(rs.getInt("SERV_COM_M"));
		objeto.setSERV_COM_T(rs.getInt("SERV_COM_T"));
		objeto.setSERV_SOC_H(rs.getInt("SERV_SOC_H"));
		objeto.setSERV_SOC_M(rs.getInt("SERV_SOC_M"));
		objeto.setSERV_SOC_T(rs.getInt("SERV_SOC_T"));
		objeto.setEGEL(rs.getInt("EGEL"));
		objeto.setEGEL_SOB(rs.getInt("EGEL_SOB"));
		objeto.setTITU_PROG(rs.getInt("TITU_PROG"));
		objeto.setCONC(rs.getInt("CONC"));
		objeto.setEGRE_TRAB_H(rs.getInt("EGRE_TRAB_H"));
		objeto.setEGRE_TRAB_M(rs.getInt("EGRE_TRAB_M"));
		objeto.setEGRE_TRAB_T(rs.getInt("EGRE_TRAB_T"));
		objeto.setEGRE_TRAB_19(rs.getInt("EGRE_TRAB_19"));
		objeto.setEGRE_TRAB_20_24(rs.getInt("EGRE_TRAB_20_24"));
		objeto.setEGRE_TRAB_25_29(rs.getInt("EGRE_TRAB_25_29"));
		objeto.setEGRE_TRAB_30(rs.getInt("EGRE_TRAB_30"));
		objeto.setEGRE_TRAB_DIS(rs.getInt("EGRE_TRAB_DIS"));
		objeto.setDOCENTES_T(rs.getInt("DOCENTES_T"));
		objeto.setDOCENTES_H(rs.getInt("DOCENTES_H"));
		objeto.setDOCENTES_M(rs.getInt("DOCENTES_M"));
		objeto.setDOCENTES_30(rs.getInt("DOCENTES_30"));
		objeto.setDOCENTES_31_49(rs.getInt("DOCENTES_31_49"));
		objeto.setDOCENTES_50(rs.getInt("DOCENTES_50"));
		objeto.setDOCENTES_DISC(rs.getInt("DOCENTES_DISC"));
		objeto.setDOCENTES_EXT(rs.getInt("DOCENTES_EXT"));
		objeto.setDOCENTES_0_5(rs.getInt("DOCENTES_0_5"));
		objeto.setDOCENTES_6_15(rs.getInt("DOCENTES_6_15"));
		objeto.setDOCENTES_16_25(rs.getInt("DOCENTES_16_25"));
		objeto.setDOCENTES_26(rs.getInt("DOCENTES_26"));
		objeto.setDOCENTES_F_D(rs.getInt("DOCENTES_F_D"));
		objeto.setDOCENTES_F_M(rs.getInt("DOCENTES_F_M"));
		objeto.setDOCENTES_F_ESP(rs.getInt("DOCENTES_F_ESP"));
		objeto.setDOCENTES_F_LIC(rs.getInt("DOCENTES_F_LIC"));
		objeto.setDOCENTES_F_OTRO(rs.getInt("DOCENTES_F_OTRO"));
		objeto.setDOCENTES_T_COMP(rs.getInt("DOCENTES_T_COMP"));
		objeto.setDOCENTES_COMP_H(rs.getInt("DOCENTES_COMP_H"));
		objeto.setDOCENTES_COMP_M(rs.getInt("DOCENTES_COMP_M"));
		objeto.setDOCENTES_MED_T(rs.getInt("DOCENTES_MED_T"));
		objeto.setDOCENTES_MED_H(rs.getInt("DOCENTES_MED_H"));
		objeto.setDOCENTES_MED_M(rs.getInt("DOCENTES_MED_M"));
		objeto.setDOCENTES_SNI(rs.getInt("DOCENTES_SNI"));
		objeto.setDOCENTES_FPD(rs.getInt("DOCENTES_FPD"));
		objeto.setDOCENTES_CGA(rs.getInt("DOCENTES_CGA"));
		objeto.setDOCENTES_MOV_NAC(rs.getInt("DOCENTES_MOV_NAC"));
		objeto.setDOCENTES_MOV_INT(rs.getInt("DOCENTES_MOV_INT"));
		objeto.setASPIRANTES_ADM(rs.getInt("ASPIRANTES_ADM"));
		objeto.setBECADOS_T(rs.getInt("BECADOS_T"));
		objeto.setBECADOS_H(rs.getInt("BECADOS_H"));
		objeto.setBECADOS_M(rs.getInt("BECADOS_M"));
		objeto.setULT_GRAD_DIS(rs.getInt("ULT_GRAD_DIS"));
		objeto.setEGRESADOS_T(rs.getInt("EGRESADOS_T"));
		objeto.setEGRESADOS_H(rs.getInt("EGRESADOS_H"));
		objeto.setEGRESADOS_M(rs.getInt("EGRESADOS_M"));
		objeto.setEGRESADOS_19(rs.getInt("EGRESADOS_19"));
		objeto.setEGRESADOS_20_24(rs.getInt("EGRESADOS_20_24"));
		objeto.setEGRESADOS_25_29(rs.getInt("EGRESADOS_25_29"));
		objeto.setEGRESADOS_30(rs.getInt("EGRESADOS_30"));
		objeto.setEGRESADOS_DIS(rs.getInt("EGRESADOS_DIS"));
		objeto.setTOTAL_EDAD(rs.getInt("TOTAL_EDAD"));
		objeto.setTOTAL_NI_E(rs.getInt("TOTAL_NI_E"));
		objeto.setNIVEL_PREV(rs.getInt("NIVEL_PREV"));
		objeto.setTOTAL_D_E(rs.getInt("TOTAL_D_E"));
		objeto.setTOTAL_D_A(rs.getInt("TOTAL_D_A"));
		objeto.setTOTAL_D_F(rs.getInt("TOTAL_D_F"));
		objeto.setQUEST_1(rs.getString("QUEST_1"));
		objeto.setTOTAL_RI_E(rs.getInt("TOTAL_RI_E"));
		objeto.setTOTAL_DES_E(rs.getInt("TOTAL_DES_E"));
		objeto.setTOTAL_MN_E(rs.getInt("TOTAL_MN_E"));
		objeto.setTOTAL_MI_E(rs.getInt("TOTAL_MI_E"));
		objeto.setQUEST_2(rs.getString("QUEST_2"));
		objeto.setTOTAL_UG_E(rs.getInt("TOTAL_UG_E"));
		objeto.setTOTAL_EGRE_E(rs.getInt("TOTAL_EGRE_E"));
		objeto.setPROM_EGRE(rs.getDouble("PROM_EGRE"));
		objeto.setQUEST_3(rs.getString("QUEST_3"));
		objeto.setQUEST_4(rs.getString("QUEST_4"));
		objeto.setTOTAL_TRAB_E(rs.getInt("TOTAL_TRAB_E"));
		objeto.setPOR_EGRE_TRAB(rs.getInt("POR_EGRE_TRAB"));
				
		return objeto;
	}
}